steps:
- id: build_berryhunterd
  waitFor: ['-']
  name: 'gcr.io/cloud-builders/docker'
  entrypoint: bash
  args: 
    - -c
    - |
      docker build \
        -t gcr.io/$PROJECT_ID/berryhunterd:rev-$SHORT_SHA \
        -f Dockerfile.berryhunterd .

- id: build_chieftaind
  waitFor: ['-']
  name: 'gcr.io/cloud-builders/docker'
  entrypoint: bash
  args: 
    - -c
    - |
      docker build \
        -t gcr.io/$PROJECT_ID/chieftaind:rev-$SHORT_SHA \
        -f Dockerfile.chieftaind .

- id: build_berryhunter_edge
  waitFor: ['-']
  name: 'gcr.io/cloud-builders/docker'
  entrypoint: bash
  args: 
    - -c
    - |
      docker build \
        -t gcr.io/$PROJECT_ID/berryhunter-edge:rev-$SHORT_SHA \
        -f Dockerfile.berryhunter-edge .   

- id: build_berryhunter_web
  waitFor: ['-']
  name: 'gcr.io/cloud-builders/docker'
  entrypoint: bash
  args: 
    - -c
    - |
      docker build \
        -t gcr.io/$PROJECT_ID/berryhunter-web:rev-$SHORT_SHA \
        -f Dockerfile.berryhunter-web . 
images:
- 'gcr.io/$PROJECT_ID/berryhunterd:rev-$SHORT_SHA'
- 'gcr.io/$PROJECT_ID/chieftaind:rev-$SHORT_SHA'
- 'gcr.io/$PROJECT_ID/berryhunter-edge:rev-$SHORT_SHA'
- 'gcr.io/$PROJECT_ID/berryhunter-web:rev-$SHORT_SHA'
