# Decrypt the file containing the key
steps:
# ---- berryhunterd
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/berryhunterd:r$SHORT_SHA', '-f', 'Dockerfile.berryhunterd', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['tag', 'gcr.io/$PROJECT_ID/berryhunterd:r$SHORT_SHA', 'gcr.io/$PROJECT_ID/berryhunterd:latest']
# ---- chieftaind
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/chieftaind:r$SHORT_SHA', '-f', 'Dockerfile.chieftaind', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['tag', 'gcr.io/$PROJECT_ID/chieftaind:r$SHORT_SHA', 'gcr.io/$PROJECT_ID/chieftaind:latest']
# ---- web
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/berryhunter-web:r$SHORT_SHA', '-f', 'Dockerfile.berryhunter-web', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['tag', 'gcr.io/$PROJECT_ID/berryhunter-web:r$SHORT_SHA', 'gcr.io/$PROJECT_ID/berryhunter-web:latest']
# ---- edge
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/berryhunter-edge:r$SHORT_SHA', '-f', 'Dockerfile.berryhunter-edge', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['tag', 'gcr.io/$PROJECT_ID/berryhunter-edge:r$SHORT_SHA', 'gcr.io/$PROJECT_ID/berryhunter-edge:latest']
images:
- 'gcr.io/$PROJECT_ID/berryhunterd:r$SHORT_SHA'
- 'gcr.io/$PROJECT_ID/berryhunterd:latest'
- 'gcr.io/$PROJECT_ID/chieftaind:r$SHORT_SHA'
- 'gcr.io/$PROJECT_ID/chieftaind:latest'
- 'gcr.io/$PROJECT_ID/berryhunter-web:r$SHORT_SHA'
- 'gcr.io/$PROJECT_ID/berryhunter-web:latest'
- 'gcr.io/$PROJECT_ID/berryhunter-edge:r$SHORT_SHA'
- 'gcr.io/$PROJECT_ID/berryhunter-edge:latest'