FROM node:20 AS builder

# load dependencies for cacheability
WORKDIR /app/frontend/
COPY frontend/package.json .
COPY frontend/package-lock.json .
RUN npm install

# copy sources
WORKDIR /app/
COPY frontend/ frontend/
COPY api/ api/
COPY changelog/ changelog/

# build frontend
WORKDIR /app/frontend/
RUN npm run build

# ---- actual image
FROM nginx:latest

WORKDIR /usr/share/nginx/html
COPY --from=builder /app/frontend/dist/ .
