// automatically generated by the FlatBuffers compiler, do not modify

package BerryhunterApi

const (
	ActionTypePrimary = 0
	ActionTypeCraftItem = 1
	ActionTypeEquipItem = 2
	ActionTypeUnequipItem = 3
	ActionTypeDropItem = 4
	ActionTypePlaceItem = 5
	ActionTypeConsumeItem = 6
)

var EnumNamesActionType = map[int]string{
	ActionTypePrimary:"Primary",
	ActionTypeCraftItem:"CraftItem",
	ActionTypeEquipItem:"EquipItem",
	ActionTypeUnequipItem:"UnequipItem",
	ActionTypeDropItem:"DropItem",
	ActionTypePlaceItem:"PlaceItem",
	ActionTypeConsumeItem:"ConsumeItem",
}

