// automatically generated by the FlatBuffers compiler, do not modify

package BerryhunterApi

const (
	AnyEntityNONE = 0
	AnyEntityCharacter = 1
	AnyEntityMob = 2
	AnyEntityResource = 3
	AnyEntityPlaceable = 4
)

var EnumNamesAnyEntity = map[int]string{
	AnyEntityNONE:"NONE",
	AnyEntityCharacter:"Character",
	AnyEntityMob:"Mob",
	AnyEntityResource:"Resource",
	AnyEntityPlaceable:"Placeable",
}

