// automatically generated by the FlatBuffers compiler, do not modify

package BerryhunterApi

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Character struct {
	_tab flatbuffers.Table
}

func GetRootAsCharacter(buf []byte, offset flatbuffers.UOffsetT) *Character {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Character{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *Character) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Character) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Character) Id() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Character) MutateId(n uint64) bool {
	return rcv._tab.MutateUint64Slot(4, n)
}

func (rcv *Character) EntityType() uint16 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetUint16(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Character) MutateEntityType(n uint16) bool {
	return rcv._tab.MutateUint16Slot(6, n)
}

func (rcv *Character) Pos(obj *Vec2f) *Vec2f {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		x := o + rcv._tab.Pos
		if obj == nil {
			obj = new(Vec2f)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *Character) Radius() uint16 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.GetUint16(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Character) MutateRadius(n uint16) bool {
	return rcv._tab.MutateUint16Slot(10, n)
}

func (rcv *Character) Rotation() float32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.GetFloat32(o + rcv._tab.Pos)
	}
	return 0.0
}

func (rcv *Character) MutateRotation(n float32) bool {
	return rcv._tab.MutateFloat32Slot(12, n)
}

func (rcv *Character) IsHit() byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		return rcv._tab.GetByte(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Character) MutateIsHit(n byte) bool {
	return rcv._tab.MutateByteSlot(14, n)
}

func (rcv *Character) ActionTick() uint16 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(16))
	if o != 0 {
		return rcv._tab.GetUint16(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Character) MutateActionTick(n uint16) bool {
	return rcv._tab.MutateUint16Slot(16, n)
}

func (rcv *Character) Name() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(18))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *Character) Equipment(j int) byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(20))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetByte(a + flatbuffers.UOffsetT(j*1))
	}
	return 0
}

func (rcv *Character) EquipmentLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(20))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *Character) EquipmentBytes() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(20))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *Character) Health() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(22))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Character) MutateHealth(n uint32) bool {
	return rcv._tab.MutateUint32Slot(22, n)
}

func (rcv *Character) Satiety() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(24))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Character) MutateSatiety(n uint32) bool {
	return rcv._tab.MutateUint32Slot(24, n)
}

func (rcv *Character) BodyTemperature() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(26))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Character) MutateBodyTemperature(n uint32) bool {
	return rcv._tab.MutateUint32Slot(26, n)
}

func (rcv *Character) Aabb(obj *AABB) *AABB {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(28))
	if o != 0 {
		x := o + rcv._tab.Pos
		if obj == nil {
			obj = new(AABB)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func CharacterStart(builder *flatbuffers.Builder) {
	builder.StartObject(13)
}
func CharacterAddId(builder *flatbuffers.Builder, id uint64) {
	builder.PrependUint64Slot(0, id, 0)
}
func CharacterAddEntityType(builder *flatbuffers.Builder, entityType uint16) {
	builder.PrependUint16Slot(1, entityType, 0)
}
func CharacterAddPos(builder *flatbuffers.Builder, pos flatbuffers.UOffsetT) {
	builder.PrependStructSlot(2, flatbuffers.UOffsetT(pos), 0)
}
func CharacterAddRadius(builder *flatbuffers.Builder, radius uint16) {
	builder.PrependUint16Slot(3, radius, 0)
}
func CharacterAddRotation(builder *flatbuffers.Builder, rotation float32) {
	builder.PrependFloat32Slot(4, rotation, 0.0)
}
func CharacterAddIsHit(builder *flatbuffers.Builder, isHit byte) {
	builder.PrependByteSlot(5, isHit, 0)
}
func CharacterAddActionTick(builder *flatbuffers.Builder, actionTick uint16) {
	builder.PrependUint16Slot(6, actionTick, 0)
}
func CharacterAddName(builder *flatbuffers.Builder, name flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(7, flatbuffers.UOffsetT(name), 0)
}
func CharacterAddEquipment(builder *flatbuffers.Builder, equipment flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(8, flatbuffers.UOffsetT(equipment), 0)
}
func CharacterStartEquipmentVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(1, numElems, 1)
}
func CharacterAddHealth(builder *flatbuffers.Builder, health uint32) {
	builder.PrependUint32Slot(9, health, 0)
}
func CharacterAddSatiety(builder *flatbuffers.Builder, satiety uint32) {
	builder.PrependUint32Slot(10, satiety, 0)
}
func CharacterAddBodyTemperature(builder *flatbuffers.Builder, bodyTemperature uint32) {
	builder.PrependUint32Slot(11, bodyTemperature, 0)
}
func CharacterAddAabb(builder *flatbuffers.Builder, aabb flatbuffers.UOffsetT) {
	builder.PrependStructSlot(12, flatbuffers.UOffsetT(aabb), 0)
}
func CharacterEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
