// automatically generated by the FlatBuffers compiler, do not modify

package BerryhunterApi

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type ChatMessage struct {
	_tab flatbuffers.Table
}

func GetRootAsChatMessage(buf []byte, offset flatbuffers.UOffsetT) *ChatMessage {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &ChatMessage{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *ChatMessage) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *ChatMessage) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *ChatMessage) Message() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func ChatMessageStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func ChatMessageAddMessage(builder *flatbuffers.Builder, message flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(message), 0)
}
func ChatMessageEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
