// automatically generated by the FlatBuffers compiler, do not modify

package BerryhunterApi

const (
	ClientMessageBodyNONE = 0
	ClientMessageBodyInput = 1
	ClientMessageBodyJoin = 2
)

var EnumNamesClientMessageBody = map[int]string{
	ClientMessageBodyNONE:"NONE",
	ClientMessageBodyInput:"Input",
	ClientMessageBodyJoin:"Join",
}

