// automatically generated by the FlatBuffers compiler, do not modify

package BerryhunterApi

const (
	ClientMessageBodyNONE = 0
	ClientMessageBodyInput = 1
	ClientMessageBodyJoin = 2
	ClientMessageBodyCheat = 3
	ClientMessageBodyChatMessage = 4
)

var EnumNamesClientMessageBody = map[int]string{
	ClientMessageBodyNONE:"NONE",
	ClientMessageBodyInput:"Input",
	ClientMessageBodyJoin:"Join",
	ClientMessageBodyCheat:"Cheat",
	ClientMessageBodyChatMessage:"ChatMessage",
}

