// automatically generated by the FlatBuffers compiler, do not modify

package BerryhunterApi

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Join struct {
	_tab flatbuffers.Table
}

func GetRootAsJoin(buf []byte, offset flatbuffers.UOffsetT) *Join {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Join{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *Join) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Join) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Join) PlayerName() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func JoinStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func JoinAddPlayerName(builder *flatbuffers.Builder, playerName flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(playerName), 0)
}
func JoinEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
