// automatically generated by the FlatBuffers compiler, do not modify

package BerryhunterApi

const (
	PlayerNONE = 0
	PlayerCharacter = 1
	PlayerSpectator = 2
)

var EnumNamesPlayer = map[int]string{
	PlayerNONE:"NONE",
	PlayerCharacter:"Character",
	PlayerSpectator:"Spectator",
}

