// automatically generated by the FlatBuffers compiler, do not modify

package BerryhunterApi

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Resource struct {
	_tab flatbuffers.Table
}

func GetRootAsResource(buf []byte, offset flatbuffers.UOffsetT) *Resource {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Resource{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *Resource) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Resource) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Resource) Id() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Resource) MutateId(n uint64) bool {
	return rcv._tab.MutateUint64Slot(4, n)
}

func (rcv *Resource) EntityType() uint16 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetUint16(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Resource) MutateEntityType(n uint16) bool {
	return rcv._tab.MutateUint16Slot(6, n)
}

func (rcv *Resource) Pos(obj *Vec2f) *Vec2f {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		x := o + rcv._tab.Pos
		if obj == nil {
			obj = new(Vec2f)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *Resource) Radius() uint16 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.GetUint16(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Resource) MutateRadius(n uint16) bool {
	return rcv._tab.MutateUint16Slot(10, n)
}

func (rcv *Resource) Aabb(obj *AABB) *AABB {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		x := o + rcv._tab.Pos
		if obj == nil {
			obj = new(AABB)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func ResourceStart(builder *flatbuffers.Builder) {
	builder.StartObject(5)
}
func ResourceAddId(builder *flatbuffers.Builder, id uint64) {
	builder.PrependUint64Slot(0, id, 0)
}
func ResourceAddEntityType(builder *flatbuffers.Builder, entityType uint16) {
	builder.PrependUint16Slot(1, entityType, 0)
}
func ResourceAddPos(builder *flatbuffers.Builder, pos flatbuffers.UOffsetT) {
	builder.PrependStructSlot(2, flatbuffers.UOffsetT(pos), 0)
}
func ResourceAddRadius(builder *flatbuffers.Builder, radius uint16) {
	builder.PrependUint16Slot(3, radius, 0)
}
func ResourceAddAabb(builder *flatbuffers.Builder, aabb flatbuffers.UOffsetT) {
	builder.PrependStructSlot(4, flatbuffers.UOffsetT(aabb), 0)
}
func ResourceEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
