// automatically generated by the FlatBuffers compiler, do not modify

package BerryhunterApi

const (
	ServerMessageBodyNONE = 0
	ServerMessageBodyWelcome = 1
	ServerMessageBodyGameState = 2
	ServerMessageBodyAccept = 3
	ServerMessageBodyObituary = 4
	ServerMessageBodyEntityMessage = 5
)

var EnumNamesServerMessageBody = map[int]string{
	ServerMessageBodyNONE:"NONE",
	ServerMessageBodyWelcome:"Welcome",
	ServerMessageBodyGameState:"GameState",
	ServerMessageBodyAccept:"Accept",
	ServerMessageBodyObituary:"Obituary",
	ServerMessageBodyEntityMessage:"EntityMessage",
}

