// automatically generated by the FlatBuffers compiler, do not modify

package BerryhunterApi

const (
	StatusEffectDamaged = 0
	StatusEffectYielded = 1
	StatusEffectFreezing = 2
	StatusEffectStarving = 3
	StatusEffectRegenerating = 4
	StatusEffectDamagedAmbient = 5
)

var EnumNamesStatusEffect = map[int]string{
	StatusEffectDamaged:"Damaged",
	StatusEffectYielded:"Yielded",
	StatusEffectFreezing:"Freezing",
	StatusEffectStarving:"Starving",
	StatusEffectRegenerating:"Regenerating",
	StatusEffectDamagedAmbient:"DamagedAmbient",
}

