// automatically generated by the FlatBuffers compiler, do not modify

package BerryhunterApi

const (
	StatusEffectDamaged = 0
	StatusEffectDamagedOverTime = 1
	StatusEffectYielded = 2
	StatusEffectFreezing = 3
	StatusEffectStarving = 4
	StatusEffectRegenerating = 5
)

var EnumNamesStatusEffect = map[int]string{
	StatusEffectDamaged:"Damaged",
	StatusEffectDamagedOverTime:"DamagedOverTime",
	StatusEffectYielded:"Yielded",
	StatusEffectFreezing:"Freezing",
	StatusEffectStarving:"Starving",
	StatusEffectRegenerating:"Regenerating",
}

