// automatically generated by the FlatBuffers compiler, do not modify

package BerryhunterApi

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type ValidToken struct {
	_tab flatbuffers.Table
}

func GetRootAsValidToken(buf []byte, offset flatbuffers.UOffsetT) *ValidToken {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &ValidToken{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *ValidToken) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *ValidToken) Table() flatbuffers.Table {
	return rcv._tab
}

func ValidTokenStart(builder *flatbuffers.Builder) {
	builder.StartObject(0)
}
func ValidTokenEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
