// automatically generated by the FlatBuffers compiler, do not modify

package DeathioApi

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Accept struct {
	_tab flatbuffers.Table
}

func GetRootAsAccept(buf []byte, offset flatbuffers.UOffsetT) *Accept {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Accept{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *Accept) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Accept) Table() flatbuffers.Table {
	return rcv._tab
}

func AcceptStart(builder *flatbuffers.Builder) {
	builder.StartObject(0)
}
func AcceptEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
