// automatically generated by the FlatBuffers compiler, do not modify

package DeathioApi

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Action struct {
	_tab flatbuffers.Table
}

func GetRootAsAction(buf []byte, offset flatbuffers.UOffsetT) *Action {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Action{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *Action) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Action) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Action) Item() byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetByte(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Action) MutateItem(n byte) bool {
	return rcv._tab.MutateByteSlot(4, n)
}

func ActionStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func ActionAddItem(builder *flatbuffers.Builder, item byte) {
	builder.PrependByteSlot(0, item, 0)
}
func ActionEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
