// automatically generated by the FlatBuffers compiler, do not modify

package DeathioApi

const (
	AnyEntityNONE = 0
	AnyEntityPlayer = 1
	AnyEntityMob = 2
	AnyEntityResource = 3
	AnyEntityPlaceable = 4
)

var EnumNamesAnyEntity = map[int]string{
	AnyEntityNONE:"NONE",
	AnyEntityPlayer:"Player",
	AnyEntityMob:"Mob",
	AnyEntityResource:"Resource",
	AnyEntityPlaceable:"Placeable",
}

