// automatically generated by the FlatBuffers compiler, do not modify

package DeathioApi

const (
	ClientMessageNONE = 0
	ClientMessageInput = 1
	ClientMessageJoin = 2
)

var EnumNamesClientMessage = map[int]string{
	ClientMessageNONE:"NONE",
	ClientMessageInput:"Input",
	ClientMessageJoin:"Join",
}

