// automatically generated by the FlatBuffers compiler, do not modify

package DeathioApi

const (
	EntityTypeDebugCircle = 0
	EntityTypeBorder = 1
	EntityTypeRoundTree = 2
	EntityTypeMarioTree = 3
	EntityTypeCharacter = 4
	EntityTypeStone = 5
	EntityTypeBronze = 6
	EntityTypeIron = 7
	EntityTypeBerryBush = 8
	EntityTypeDodo = 9
	EntityTypeSaberToothCat = 10
	EntityTypeMammoth = 11
)

var EnumNamesEntityType = map[int]string{
	EntityTypeDebugCircle:"DebugCircle",
	EntityTypeBorder:"Border",
	EntityTypeRoundTree:"RoundTree",
	EntityTypeMarioTree:"MarioTree",
	EntityTypeCharacter:"Character",
	EntityTypeStone:"Stone",
	EntityTypeBronze:"Bronze",
	EntityTypeIron:"Iron",
	EntityTypeBerryBush:"BerryBush",
	EntityTypeDodo:"Dodo",
	EntityTypeSaberToothCat:"SaberToothCat",
	EntityTypeMammoth:"Mammoth",
}

