// automatically generated by the FlatBuffers compiler, do not modify

package DeathioApi

const (
	EquipmentSlotPrimaryHand = 0
	EquipmentSlotHead = 1
	EquipmentSlotBreast = 2
	EquipmentSlotBack = 3
)

var EnumNamesEquipmentSlot = map[int]string{
	EquipmentSlotPrimaryHand:"PrimaryHand",
	EquipmentSlotHead:"Head",
	EquipmentSlotBreast:"Breast",
	EquipmentSlotBack:"Back",
}

