// automatically generated by the FlatBuffers compiler, do not modify

package DeathioApi

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Equipment struct {
	_tab flatbuffers.Struct
}

func (rcv *Equipment) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Equipment) Table() flatbuffers.Table {
	return rcv._tab.Table
}

func (rcv *Equipment) Item() byte {
	return rcv._tab.GetByte(rcv._tab.Pos + flatbuffers.UOffsetT(0))
}
func (rcv *Equipment) MutateItem(n byte) bool {
	return rcv._tab.MutateByte(rcv._tab.Pos+flatbuffers.UOffsetT(0), n)
}

func (rcv *Equipment) Slot() byte {
	return rcv._tab.GetByte(rcv._tab.Pos + flatbuffers.UOffsetT(1))
}
func (rcv *Equipment) MutateSlot(n byte) bool {
	return rcv._tab.MutateByte(rcv._tab.Pos+flatbuffers.UOffsetT(1), n)
}

func CreateEquipment(builder *flatbuffers.Builder, item byte, slot byte) flatbuffers.UOffsetT {
	builder.Prep(1, 2)
	builder.PrependByte(slot)
	builder.PrependByte(item)
	return builder.Offset()
}
