// automatically generated by the FlatBuffers compiler, do not modify

package DeathioApi

const (
	EquipmentSlotPrimaryHand = 0
)

var EnumNamesEquipmentSlot = map[int]string{
	EquipmentSlotPrimaryHand:"PrimaryHand",
}

