// automatically generated by the FlatBuffers compiler, do not modify

package DeathioApi

const (
	ItemFist = 0
	ItemWoodClub = 1
	ItemStoneTool = 2
	ItemBronzeTool = 3
	ItemIronTool = 4
)

var EnumNamesItem = map[int]string{
	ItemFist:"Fist",
	ItemWoodClub:"WoodClub",
	ItemStoneTool:"StoneTool",
	ItemBronzeTool:"BronzeTool",
	ItemIronTool:"IronTool",
}

