// automatically generated by the FlatBuffers compiler, do not modify

package DeathioApi

const (
	ItemNone = 0
	ItemWoodClub = 1
	ItemWoodTool = 2
	ItemStoneTool = 3
	ItemBronzeTool = 4
	ItemIronTool = 5
	ItemWood = 6
	ItemStone = 7
	ItemBronze = 8
	ItemBerry = 9
	ItemFirePlace = 10
)

var EnumNamesItem = map[int]string{
	ItemNone:"None",
	ItemWoodClub:"WoodClub",
	ItemWoodTool:"WoodTool",
	ItemStoneTool:"StoneTool",
	ItemBronzeTool:"BronzeTool",
	ItemIronTool:"IronTool",
	ItemWood:"Wood",
	ItemStone:"Stone",
	ItemBronze:"Bronze",
	ItemBerry:"Berry",
	ItemFirePlace:"FirePlace",
}

