// automatically generated by the FlatBuffers compiler, do not modify

package DeathioApi

const (
	ItemNone = 0
	ItemWoodClub = 1
	ItemStoneTool = 2
	ItemBronzeTool = 3
	ItemIronTool = 4
	ItemWood = 5
	ItemStone = 6
	ItemBronze = 7
	ItemBerry = 8
	ItemFirePlace = 9
)

var EnumNamesItem = map[int]string{
	ItemNone:"None",
	ItemWoodClub:"WoodClub",
	ItemStoneTool:"StoneTool",
	ItemBronzeTool:"BronzeTool",
	ItemIronTool:"IronTool",
	ItemWood:"Wood",
	ItemStone:"Stone",
	ItemBronze:"Bronze",
	ItemBerry:"Berry",
	ItemFirePlace:"FirePlace",
}

