// automatically generated by the FlatBuffers compiler, do not modify

package DeathioApi

const (
	ServerMessageNONE = 0
	ServerMessageWelcome = 1
	ServerMessageGameState = 2
	ServerMessageAccept = 3
	ServerMessageObituary = 4
)

var EnumNamesServerMessage = map[int]string{
	ServerMessageNONE:"NONE",
	ServerMessageWelcome:"Welcome",
	ServerMessageGameState:"GameState",
	ServerMessageAccept:"Accept",
	ServerMessageObituary:"Obituary",
}

