apiVersion: v1
kind: Service
metadata:
  name: web-prod
spec:
  ports:
  - port: 80
  selector:
    app: web
    stage: prod
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
      stage: prod
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: web
        stage: prod
    spec:
      containers:
      - image: gcr.io/berryhunter-io/berryhunter-web:latest
        name: web
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 3
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 3