// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package BerryhunterApi

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Action struct {
	_tab flatbuffers.Table
}

func GetRootAsAction(buf []byte, offset flatbuffers.UOffsetT) *Action {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Action{}
	x.Init(buf, n+offset)
	return x
}

func FinishActionBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsAction(buf []byte, offset flatbuffers.UOffsetT) *Action {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &Action{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedActionBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *Action) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Action) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Action) Item() byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetByte(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Action) MutateItem(n byte) bool {
	return rcv._tab.MutateByteSlot(4, n)
}

func (rcv *Action) ActionType() ActionType {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return ActionType(rcv._tab.GetByte(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *Action) MutateActionType(n ActionType) bool {
	return rcv._tab.MutateByteSlot(6, byte(n))
}

func ActionStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func ActionAddItem(builder *flatbuffers.Builder, item byte) {
	builder.PrependByteSlot(0, item, 0)
}
func ActionAddActionType(builder *flatbuffers.Builder, actionType ActionType) {
	builder.PrependByteSlot(1, byte(actionType), 0)
}
func ActionEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
