// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package BerryhunterApi

import "strconv"

type ClientMessageBody byte

const (
	ClientMessageBodyNONE        ClientMessageBody = 0
	ClientMessageBodyInput       ClientMessageBody = 1
	ClientMessageBodyJoin        ClientMessageBody = 2
	ClientMessageBodyCheat       ClientMessageBody = 3
	ClientMessageBodyChatMessage ClientMessageBody = 4
)

var EnumNamesClientMessageBody = map[ClientMessageBody]string{
	ClientMessageBodyNONE:        "NONE",
	ClientMessageBodyInput:       "Input",
	ClientMessageBodyJoin:        "Join",
	ClientMessageBodyCheat:       "Cheat",
	ClientMessageBodyChatMessage: "ChatMessage",
}

var EnumValuesClientMessageBody = map[string]ClientMessageBody{
	"NONE":        ClientMessageBodyNONE,
	"Input":       ClientMessageBodyInput,
	"Join":        ClientMessageBodyJoin,
	"Cheat":       ClientMessageBodyCheat,
	"ChatMessage": ClientMessageBodyChatMessage,
}

func (v ClientMessageBody) String() string {
	if s, ok := EnumNamesClientMessageBody[v]; ok {
		return s
	}
	return "ClientMessageBody(" + strconv.FormatInt(int64(v), 10) + ")"
}
