// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package BerryhunterApi

import "strconv"

type EntityType uint16

const (
	EntityTypeDebugCircle   EntityType = 0
	EntityTypeBorder        EntityType = 1
	EntityTypeRoundTree     EntityType = 2
	EntityTypeMarioTree     EntityType = 3
	EntityTypeCharacter     EntityType = 4
	EntityTypeStone         EntityType = 5
	EntityTypeBronze        EntityType = 6
	EntityTypeIron          EntityType = 7
	EntityTypeBerryBush     EntityType = 8
	EntityTypeDodo          EntityType = 9
	EntityTypeSaberToothCat EntityType = 10
	EntityTypeMammoth       EntityType = 11
	EntityTypePlaceable     EntityType = 12
	EntityTypeTitanium      EntityType = 13
	EntityTypeFlower        EntityType = 14
	EntityTypeAngryMammoth  EntityType = 15
	EntityTypeTitaniumShard EntityType = 16
)

var EnumNamesEntityType = map[EntityType]string{
	EntityTypeDebugCircle:   "DebugCircle",
	EntityTypeBorder:        "Border",
	EntityTypeRoundTree:     "RoundTree",
	EntityTypeMarioTree:     "MarioTree",
	EntityTypeCharacter:     "Character",
	EntityTypeStone:         "Stone",
	EntityTypeBronze:        "Bronze",
	EntityTypeIron:          "Iron",
	EntityTypeBerryBush:     "BerryBush",
	EntityTypeDodo:          "Dodo",
	EntityTypeSaberToothCat: "SaberToothCat",
	EntityTypeMammoth:       "Mammoth",
	EntityTypePlaceable:     "Placeable",
	EntityTypeTitanium:      "Titanium",
	EntityTypeFlower:        "Flower",
	EntityTypeAngryMammoth:  "AngryMammoth",
	EntityTypeTitaniumShard: "TitaniumShard",
}

var EnumValuesEntityType = map[string]EntityType{
	"DebugCircle":   EntityTypeDebugCircle,
	"Border":        EntityTypeBorder,
	"RoundTree":     EntityTypeRoundTree,
	"MarioTree":     EntityTypeMarioTree,
	"Character":     EntityTypeCharacter,
	"Stone":         EntityTypeStone,
	"Bronze":        EntityTypeBronze,
	"Iron":          EntityTypeIron,
	"BerryBush":     EntityTypeBerryBush,
	"Dodo":          EntityTypeDodo,
	"SaberToothCat": EntityTypeSaberToothCat,
	"Mammoth":       EntityTypeMammoth,
	"Placeable":     EntityTypePlaceable,
	"Titanium":      EntityTypeTitanium,
	"Flower":        EntityTypeFlower,
	"AngryMammoth":  EntityTypeAngryMammoth,
	"TitaniumShard": EntityTypeTitaniumShard,
}

func (v EntityType) String() string {
	if s, ok := EnumNamesEntityType[v]; ok {
		return s
	}
	return "EntityType(" + strconv.FormatInt(int64(v), 10) + ")"
}
