// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package BerryhunterApi

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Obituary struct {
	_tab flatbuffers.Table
}

func GetRootAsObituary(buf []byte, offset flatbuffers.UOffsetT) *Obituary {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Obituary{}
	x.Init(buf, n+offset)
	return x
}

func FinishObituaryBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsObituary(buf []byte, offset flatbuffers.UOffsetT) *Obituary {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &Obituary{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedObituaryBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *Obituary) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Obituary) Table() flatbuffers.Table {
	return rcv._tab
}

func ObituaryStart(builder *flatbuffers.Builder) {
	builder.StartObject(0)
}
func ObituaryEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
