// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package BerryhunterApi

import "strconv"

type Player byte

const (
	PlayerNONE      Player = 0
	PlayerCharacter Player = 1
	PlayerSpectator Player = 2
)

var EnumNamesPlayer = map[Player]string{
	PlayerNONE:      "NONE",
	PlayerCharacter: "Character",
	PlayerSpectator: "Spectator",
}

var EnumValuesPlayer = map[string]Player{
	"NONE":      PlayerNONE,
	"Character": PlayerCharacter,
	"Spectator": PlayerSpectator,
}

func (v Player) String() string {
	if s, ok := EnumNamesPlayer[v]; ok {
		return s
	}
	return "Player(" + strconv.FormatInt(int64(v), 10) + ")"
}
