// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package BerryhunterApi

import "strconv"

type ServerMessageBody byte

const (
	ServerMessageBodyNONE          ServerMessageBody = 0
	ServerMessageBodyWelcome       ServerMessageBody = 1
	ServerMessageBodyGameState     ServerMessageBody = 2
	ServerMessageBodyAccept        ServerMessageBody = 3
	ServerMessageBodyObituary      ServerMessageBody = 4
	ServerMessageBodyEntityMessage ServerMessageBody = 5
	ServerMessageBodyScoreboard    ServerMessageBody = 6
	ServerMessageBodyPong          ServerMessageBody = 7
)

var EnumNamesServerMessageBody = map[ServerMessageBody]string{
	ServerMessageBodyNONE:          "NONE",
	ServerMessageBodyWelcome:       "Welcome",
	ServerMessageBodyGameState:     "GameState",
	ServerMessageBodyAccept:        "Accept",
	ServerMessageBodyObituary:      "Obituary",
	ServerMessageBodyEntityMessage: "EntityMessage",
	ServerMessageBodyScoreboard:    "Scoreboard",
	ServerMessageBodyPong:          "Pong",
}

var EnumValuesServerMessageBody = map[string]ServerMessageBody{
	"NONE":          ServerMessageBodyNONE,
	"Welcome":       ServerMessageBodyWelcome,
	"GameState":     ServerMessageBodyGameState,
	"Accept":        ServerMessageBodyAccept,
	"Obituary":      ServerMessageBodyObituary,
	"EntityMessage": ServerMessageBodyEntityMessage,
	"Scoreboard":    ServerMessageBodyScoreboard,
	"Pong":          ServerMessageBodyPong,
}

func (v ServerMessageBody) String() string {
	if s, ok := EnumNamesServerMessageBody[v]; ok {
		return s
	}
	return "ServerMessageBody(" + strconv.FormatInt(int64(v), 10) + ")"
}
