// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package BerryhunterApi

import "strconv"

type StatusEffect uint16

const (
	StatusEffectDamaged        StatusEffect = 0
	StatusEffectYielded        StatusEffect = 1
	StatusEffectFreezing       StatusEffect = 2
	StatusEffectStarving       StatusEffect = 3
	StatusEffectRegenerating   StatusEffect = 4
	StatusEffectDamagedAmbient StatusEffect = 5
)

var EnumNamesStatusEffect = map[StatusEffect]string{
	StatusEffectDamaged:        "Damaged",
	StatusEffectYielded:        "Yielded",
	StatusEffectFreezing:       "Freezing",
	StatusEffectStarving:       "Starving",
	StatusEffectRegenerating:   "Regenerating",
	StatusEffectDamagedAmbient: "DamagedAmbient",
}

var EnumValuesStatusEffect = map[string]StatusEffect{
	"Damaged":        StatusEffectDamaged,
	"Yielded":        StatusEffectYielded,
	"Freezing":       StatusEffectFreezing,
	"Starving":       StatusEffectStarving,
	"Regenerating":   StatusEffectRegenerating,
	"DamagedAmbient": StatusEffectDamagedAmbient,
}

func (v StatusEffect) String() string {
	if s, ok := EnumNamesStatusEffect[v]; ok {
		return s
	}
	return "StatusEffect(" + strconv.FormatInt(int64(v), 10) + ")"
}
