apiVersion: v1
kind: Service
metadata:
  name: berryhunterd-svc
spec:
  ports:
  - port: 80
  selector:
    app: berryhunterd-app
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: berryhunterd-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: berryhunterd-app
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: berryhunterd-app
    spec:
      containers:
      - image: gcr.io/trichner-212015/berryhunterd:branch-develop
        name: berryhunterd
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /etc/berryhunterd/
          name: cfg-volume
        env:
          - name: BERRYHUNTERD_CONF
            value: /etc/berryhunterd/conf.json
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 3
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 3
      volumes:
      - name: cfg-volume
        configMap:
          name: berryhunterd-cfgmap
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: berryhunterd-cfgmap
data:
  conf.json: |-
    {
      "server": {
        "port": 80,
        "path": "/game"
      },
      "game": {
        "coldFractionNightPerSecond": 0.025,
        "coldFractionRestingPerSecond": 0.005,
        "player": {
          "freezingDamageTickFraction": 0.001,
          "starveDamageTickFraction": 0.001,
          "satietyLossTickFraction": 0.0002,
          "healthGainSatietyThreshold": 0.5,
          "healthGainTemperatureThreshold": 0.5,
          "healthGainTick": 0.0006,
          "healthGainSatietyLossTickFraction": 0.0002,
          "walkingSpeedPerTick": 0.055
        }
      }
    }