apiVersion: v1
kind: Service
metadata:
  name: chieftaind-svc
spec:
  ports:
  - name: http-rest
    port: 3080
  - name: tls-api
    port: 3443
  selector:
    app: chieftaind-app
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chieftaind-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chieftaind-app
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: chieftaind-app
    spec:
      containers:
      - image: gcr.io/trichner-212015/chieftaind:branch-develop
        name: chieftaind
        ports:
        - containerPort: 3080
        - containerPort: 3443
        volumeMounts:
        - mountPath: /etc/chieftaind/
          name: cfg-volume
        env:
          - name: CHIEFTAIND_CONF
            value: /etc/chieftaind/conf.json
        readinessProbe:
          httpGet:
            path: /
            port: 3080
          initialDelaySeconds: 5
          periodSeconds: 3
        livenessProbe:
          httpGet:
            path: /
            port: 3080
          initialDelaySeconds: 5
          periodSeconds: 3
      volumes:
      - name: cfg-volume
        configMap:
          name: chieftaind-cfgmap
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: chieftaind-cfgmap
data:
  conf.json: |-
    {
      "apiAddr":":3443",
      "restAddr":":3080",
      "dataDir":"./"
    }