apiVersion: v1
kind: Service
metadata:
  name: edge-svc
spec:
  ports:
  - name: http
    port: 80
  - name: https
    port: 443
  selector:
    app: edge-app
  clusterIP: None
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: edge
spec:
  selector:
    matchLabels:
      app: edge-app
  serviceName: edge
  replicas: 1
  template:
    metadata:
      labels:
        app: edge-app
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: edge
        image: abiosoft/caddy
        ports:
        - name: http
          containerPort: 80
        - name: https
          containerPort: 443
        volumeMounts:
        - name: edge-data
          mountPath: /data
        - name: cfg-volume
          mountPath: /etc/Caddyfile
          subPath: Caddyfile
        env:
          - name: CADDYPATH
            value: /data
          - name: ACME_AGREE
            value: 'true'
        readinessProbe:
          tcpSocket:
            port: 443
          initialDelaySeconds: 5
          periodSeconds: 5
          failureThreshold: 20
        livenessProbe:
          tcpSocket:
            port: 443
          initialDelaySeconds: 60
          periodSeconds: 10
          failureThreshold: 3
      volumes:
        - name: cfg-volume
          configMap:
            name: edge-cfgmap
  volumeClaimTemplates:
  - metadata:
      name: edge-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: standard
      resources:
        requests:
          storage: 1Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: edge-cfgmap
data:
  Caddyfile: |-
    https://develop.berryhunter.io {
        
        #tls mail@n1b.ch
        tls self_signed
    
        proxy /game berryhunterd-svc:80/game {
          websocket
          transparent
        }
    
        proxy /chieftain chieftaind-svc:3080 {
          without /chieftain
            transparent
        }
    
        proxy / berryhunter-web:80/ {
          transparent
        }
    }