version: '3'
services:
    edge:
        image: gcr.io/trichner-212015/berryhunter-edge
        depends_on:
            - berryhunterd
            - chieftaind
            - web
        volumes:
            - "./cfg/edge/Caddyfile:/app/Caddyfile"
        ports:
            - "443:443"
    berryhunterd:
        image: gcr.io/trichner-212015/berryhunterd
        depends_on:
            - chieftaind
            - web
        volumes:
            - "./cfg/berryhunterd/conf.json:/root/berryhunterd/conf.json"
        ports:
            - "127.0.0.1:2000:80"
    web:
        image: gcr.io/trichner-212015/berryhunter-web
    chieftaind:
        image: chieftaind
        ports:
            - "127.0.0.1:3080:3080"
