// automatically generated by the FlatBuffers compiler, do not modify

/**
 * @const
 * @namespace
 */
var BerryhunterApi = BerryhunterApi || {};

// Exports for Node.js and RequireJS
this.BerryhunterApi = BerryhunterApi;
