// automatically generated by the FlatBuffers compiler, do not modify

/**
 * @const
 * @namespace
 */
var BerryhunterApi = BerryhunterApi || {};

/**
 * @enum
 */
BerryhunterApi.ActionType = {
  Primary: 0,
  CraftItem: 1,
  EquipItem: 2,
  UnequipItem: 3,
  DropItem: 4,
  PlaceItem: 5,
  ConsumeItem: 6
};

/**
 * @enum
 */
BerryhunterApi.ClientMessageBody = {
  NONE: 0,
  Input: 1,
  Join: 2
};

/**
 * @constructor
 */
BerryhunterApi.Action = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {BerryhunterApi.Action}
 */
BerryhunterApi.Action.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {BerryhunterApi.Action=} obj
 * @returns {BerryhunterApi.Action}
 */
BerryhunterApi.Action.getRootAsAction = function(bb, obj) {
  return (obj || new BerryhunterApi.Action).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @returns {number}
 */
BerryhunterApi.Action.prototype.item = function() {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.readUint8(this.bb_pos + offset) : 0;
};

/**
 * @returns {BerryhunterApi.ActionType}
 */
BerryhunterApi.Action.prototype.actionType = function() {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? /** @type {BerryhunterApi.ActionType} */ (this.bb.readUint8(this.bb_pos + offset)) : BerryhunterApi.ActionType.Primary;
};

/**
 * @param {flatbuffers.Builder} builder
 */
BerryhunterApi.Action.startAction = function(builder) {
  builder.startObject(2);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} item
 */
BerryhunterApi.Action.addItem = function(builder, item) {
  builder.addFieldInt8(0, item, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {BerryhunterApi.ActionType} actionType
 */
BerryhunterApi.Action.addActionType = function(builder, actionType) {
  builder.addFieldInt8(1, actionType, BerryhunterApi.ActionType.Primary);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
BerryhunterApi.Action.endAction = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @constructor
 */
BerryhunterApi.Input = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {BerryhunterApi.Input}
 */
BerryhunterApi.Input.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {BerryhunterApi.Input=} obj
 * @returns {BerryhunterApi.Input}
 */
BerryhunterApi.Input.getRootAsInput = function(bb, obj) {
  return (obj || new BerryhunterApi.Input).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @returns {flatbuffers.Long}
 */
BerryhunterApi.Input.prototype.tick = function() {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.readUint64(this.bb_pos + offset) : this.bb.createLong(0, 0);
};

/**
 * @param {BerryhunterApi.Vec2f=} obj
 * @returns {BerryhunterApi.Vec2f|null}
 */
BerryhunterApi.Input.prototype.movement = function(obj) {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? (obj || new BerryhunterApi.Vec2f).__init(this.bb_pos + offset, this.bb) : null;
};

/**
 * @returns {number}
 */
BerryhunterApi.Input.prototype.rotation = function() {
  var offset = this.bb.__offset(this.bb_pos, 8);
  return offset ? this.bb.readFloat32(this.bb_pos + offset) : 0.0;
};

/**
 * @param {BerryhunterApi.Action=} obj
 * @returns {BerryhunterApi.Action|null}
 */
BerryhunterApi.Input.prototype.action = function(obj) {
  var offset = this.bb.__offset(this.bb_pos, 10);
  return offset ? (obj || new BerryhunterApi.Action).__init(this.bb.__indirect(this.bb_pos + offset), this.bb) : null;
};

/**
 * @param {flatbuffers.Builder} builder
 */
BerryhunterApi.Input.startInput = function(builder) {
  builder.startObject(4);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Long} tick
 */
BerryhunterApi.Input.addTick = function(builder, tick) {
  builder.addFieldInt64(0, tick, builder.createLong(0, 0));
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} movementOffset
 */
BerryhunterApi.Input.addMovement = function(builder, movementOffset) {
  builder.addFieldStruct(1, movementOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} rotation
 */
BerryhunterApi.Input.addRotation = function(builder, rotation) {
  builder.addFieldFloat32(2, rotation, 0.0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} actionOffset
 */
BerryhunterApi.Input.addAction = function(builder, actionOffset) {
  builder.addFieldOffset(3, actionOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
BerryhunterApi.Input.endInput = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @constructor
 */
BerryhunterApi.Join = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {BerryhunterApi.Join}
 */
BerryhunterApi.Join.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {BerryhunterApi.Join=} obj
 * @returns {BerryhunterApi.Join}
 */
BerryhunterApi.Join.getRootAsJoin = function(bb, obj) {
  return (obj || new BerryhunterApi.Join).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array|null}
 */
BerryhunterApi.Join.prototype.playerName = function(optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param {flatbuffers.Builder} builder
 */
BerryhunterApi.Join.startJoin = function(builder) {
  builder.startObject(1);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} playerNameOffset
 */
BerryhunterApi.Join.addPlayerName = function(builder, playerNameOffset) {
  builder.addFieldOffset(0, playerNameOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
BerryhunterApi.Join.endJoin = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @constructor
 */
BerryhunterApi.ClientMessage = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {BerryhunterApi.ClientMessage}
 */
BerryhunterApi.ClientMessage.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {BerryhunterApi.ClientMessage=} obj
 * @returns {BerryhunterApi.ClientMessage}
 */
BerryhunterApi.ClientMessage.getRootAsClientMessage = function(bb, obj) {
  return (obj || new BerryhunterApi.ClientMessage).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @returns {BerryhunterApi.ClientMessageBody}
 */
BerryhunterApi.ClientMessage.prototype.bodyType = function() {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? /** @type {BerryhunterApi.ClientMessageBody} */ (this.bb.readUint8(this.bb_pos + offset)) : BerryhunterApi.ClientMessageBody.NONE;
};

/**
 * @param {flatbuffers.Table} obj
 * @returns {?flatbuffers.Table}
 */
BerryhunterApi.ClientMessage.prototype.body = function(obj) {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? this.bb.__union(obj, this.bb_pos + offset) : null;
};

/**
 * @param {flatbuffers.Builder} builder
 */
BerryhunterApi.ClientMessage.startClientMessage = function(builder) {
  builder.startObject(2);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {BerryhunterApi.ClientMessageBody} bodyType
 */
BerryhunterApi.ClientMessage.addBodyType = function(builder, bodyType) {
  builder.addFieldInt8(0, bodyType, BerryhunterApi.ClientMessageBody.NONE);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} bodyOffset
 */
BerryhunterApi.ClientMessage.addBody = function(builder, bodyOffset) {
  builder.addFieldOffset(1, bodyOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
BerryhunterApi.ClientMessage.endClientMessage = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} offset
 */
BerryhunterApi.ClientMessage.finishClientMessageBuffer = function(builder, offset) {
  builder.finish(offset);
};

// Exports for Node.js and RequireJS
this.BerryhunterApi = BerryhunterApi;
