// automatically generated by the FlatBuffers compiler, do not modify

/**
 * @const
 * @namespace
 */
var DeathioApi = DeathioApi || {};

/**
 * @enum
 */
DeathioApi.EntityType = {
  DebugCircle: 0,
  Border: 1,
  RoundTree: 2,
  MarioTree: 3,
  Character: 4,
  Stone: 5,
  Bronze: 6,
  Iron: 7,
  BerryBush: 8,
  Dodo: 9,
  SaberToothCat: 10,
  Mammoth: 11
};

/**
 * @enum
 */
DeathioApi.AnyEntity = {
  NONE: 0,
  Player: 1,
  Mob: 2,
  Resource: 3
};

/**
 * @constructor
 */
DeathioApi.AABB = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {DeathioApi.AABB}
 */
DeathioApi.AABB.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {DeathioApi.Vec2f=} obj
 * @returns {DeathioApi.Vec2f}
 */
DeathioApi.AABB.prototype.lower = function(obj) {
  return (obj || new DeathioApi.Vec2f).__init(this.bb_pos, this.bb);
};

/**
 * @param {DeathioApi.Vec2f=} obj
 * @returns {DeathioApi.Vec2f}
 */
DeathioApi.AABB.prototype.upper = function(obj) {
  return (obj || new DeathioApi.Vec2f).__init(this.bb_pos + 8, this.bb);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} lower_x
 * @param {number} lower_y
 * @param {number} upper_x
 * @param {number} upper_y
 * @returns {flatbuffers.Offset}
 */
DeathioApi.AABB.createAABB = function(builder, lower_x, lower_y, upper_x, upper_y) {
  builder.prep(4, 16);
  builder.prep(4, 8);
  builder.writeFloat32(upper_y);
  builder.writeFloat32(upper_x);
  builder.prep(4, 8);
  builder.writeFloat32(lower_y);
  builder.writeFloat32(lower_x);
  return builder.offset();
};

/**
 * @constructor
 */
DeathioApi.ItemStack = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {DeathioApi.ItemStack}
 */
DeathioApi.ItemStack.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @returns {number}
 */
DeathioApi.ItemStack.prototype.item = function() {
  return this.bb.readUint8(this.bb_pos);
};

/**
 * @returns {number}
 */
DeathioApi.ItemStack.prototype.count = function() {
  return this.bb.readUint32(this.bb_pos + 4);
};

/**
 * @returns {number}
 */
DeathioApi.ItemStack.prototype.slot = function() {
  return this.bb.readUint8(this.bb_pos + 8);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} item
 * @param {number} count
 * @param {number} slot
 * @returns {flatbuffers.Offset}
 */
DeathioApi.ItemStack.createItemStack = function(builder, item, count, slot) {
  builder.prep(4, 12);
  builder.pad(3);
  builder.writeInt8(slot);
  builder.writeInt32(count);
  builder.pad(3);
  builder.writeInt8(item);
  return builder.offset();
};

/**
 * @constructor
 */
DeathioApi.Entity = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {DeathioApi.Entity}
 */
DeathioApi.Entity.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {DeathioApi.Entity=} obj
 * @returns {DeathioApi.Entity}
 */
DeathioApi.Entity.getRootAsEntity = function(bb, obj) {
  return (obj || new DeathioApi.Entity).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @returns {DeathioApi.AnyEntity}
 */
DeathioApi.Entity.prototype.eType = function() {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? /** @type {DeathioApi.AnyEntity} */ (this.bb.readUint8(this.bb_pos + offset)) : DeathioApi.AnyEntity.NONE;
};

/**
 * @param {flatbuffers.Table} obj
 * @returns {?flatbuffers.Table}
 */
DeathioApi.Entity.prototype.e = function(obj) {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? this.bb.__union(obj, this.bb_pos + offset) : null;
};

/**
 * @param {flatbuffers.Builder} builder
 */
DeathioApi.Entity.startEntity = function(builder) {
  builder.startObject(2);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {DeathioApi.AnyEntity} eType
 */
DeathioApi.Entity.addEType = function(builder, eType) {
  builder.addFieldInt8(0, eType, DeathioApi.AnyEntity.NONE);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} eOffset
 */
DeathioApi.Entity.addE = function(builder, eOffset) {
  builder.addFieldOffset(1, eOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
DeathioApi.Entity.endEntity = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @constructor
 */
DeathioApi.Resource = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {DeathioApi.Resource}
 */
DeathioApi.Resource.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {DeathioApi.Resource=} obj
 * @returns {DeathioApi.Resource}
 */
DeathioApi.Resource.getRootAsResource = function(bb, obj) {
  return (obj || new DeathioApi.Resource).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @returns {flatbuffers.Long}
 */
DeathioApi.Resource.prototype.id = function() {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.readUint64(this.bb_pos + offset) : this.bb.createLong(0, 0);
};

/**
 * @param {DeathioApi.Vec2f=} obj
 * @returns {DeathioApi.Vec2f}
 */
DeathioApi.Resource.prototype.pos = function(obj) {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? (obj || new DeathioApi.Vec2f).__init(this.bb_pos + offset, this.bb) : null;
};

/**
 * @returns {number}
 */
DeathioApi.Resource.prototype.radius = function() {
  var offset = this.bb.__offset(this.bb_pos, 8);
  return offset ? this.bb.readUint16(this.bb_pos + offset) : 0;
};

/**
 * @returns {DeathioApi.EntityType}
 */
DeathioApi.Resource.prototype.entityType = function() {
  var offset = this.bb.__offset(this.bb_pos, 10);
  return offset ? /** @type {DeathioApi.EntityType} */ (this.bb.readUint16(this.bb_pos + offset)) : DeathioApi.EntityType.DebugCircle;
};

/**
 * @param {DeathioApi.AABB=} obj
 * @returns {DeathioApi.AABB}
 */
DeathioApi.Resource.prototype.aabb = function(obj) {
  var offset = this.bb.__offset(this.bb_pos, 12);
  return offset ? (obj || new DeathioApi.AABB).__init(this.bb_pos + offset, this.bb) : null;
};

/**
 * @param {flatbuffers.Builder} builder
 */
DeathioApi.Resource.startResource = function(builder) {
  builder.startObject(5);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Long} id
 */
DeathioApi.Resource.addId = function(builder, id) {
  builder.addFieldInt64(0, id, builder.createLong(0, 0));
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} posOffset
 */
DeathioApi.Resource.addPos = function(builder, posOffset) {
  builder.addFieldStruct(1, posOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} radius
 */
DeathioApi.Resource.addRadius = function(builder, radius) {
  builder.addFieldInt16(2, radius, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {DeathioApi.EntityType} entityType
 */
DeathioApi.Resource.addEntityType = function(builder, entityType) {
  builder.addFieldInt16(3, entityType, DeathioApi.EntityType.DebugCircle);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} aabbOffset
 */
DeathioApi.Resource.addAabb = function(builder, aabbOffset) {
  builder.addFieldStruct(4, aabbOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
DeathioApi.Resource.endResource = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @constructor
 */
DeathioApi.Mob = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {DeathioApi.Mob}
 */
DeathioApi.Mob.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {DeathioApi.Mob=} obj
 * @returns {DeathioApi.Mob}
 */
DeathioApi.Mob.getRootAsMob = function(bb, obj) {
  return (obj || new DeathioApi.Mob).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @returns {flatbuffers.Long}
 */
DeathioApi.Mob.prototype.id = function() {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.readUint64(this.bb_pos + offset) : this.bb.createLong(0, 0);
};

/**
 * @param {DeathioApi.Vec2f=} obj
 * @returns {DeathioApi.Vec2f}
 */
DeathioApi.Mob.prototype.pos = function(obj) {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? (obj || new DeathioApi.Vec2f).__init(this.bb_pos + offset, this.bb) : null;
};

/**
 * @returns {number}
 */
DeathioApi.Mob.prototype.radius = function() {
  var offset = this.bb.__offset(this.bb_pos, 8);
  return offset ? this.bb.readUint16(this.bb_pos + offset) : 0;
};

/**
 * @returns {DeathioApi.EntityType}
 */
DeathioApi.Mob.prototype.entityType = function() {
  var offset = this.bb.__offset(this.bb_pos, 10);
  return offset ? /** @type {DeathioApi.EntityType} */ (this.bb.readUint16(this.bb_pos + offset)) : DeathioApi.EntityType.DebugCircle;
};

/**
 * @param {DeathioApi.AABB=} obj
 * @returns {DeathioApi.AABB}
 */
DeathioApi.Mob.prototype.aabb = function(obj) {
  var offset = this.bb.__offset(this.bb_pos, 12);
  return offset ? (obj || new DeathioApi.AABB).__init(this.bb_pos + offset, this.bb) : null;
};

/**
 * @param {flatbuffers.Builder} builder
 */
DeathioApi.Mob.startMob = function(builder) {
  builder.startObject(5);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Long} id
 */
DeathioApi.Mob.addId = function(builder, id) {
  builder.addFieldInt64(0, id, builder.createLong(0, 0));
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} posOffset
 */
DeathioApi.Mob.addPos = function(builder, posOffset) {
  builder.addFieldStruct(1, posOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} radius
 */
DeathioApi.Mob.addRadius = function(builder, radius) {
  builder.addFieldInt16(2, radius, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {DeathioApi.EntityType} entityType
 */
DeathioApi.Mob.addEntityType = function(builder, entityType) {
  builder.addFieldInt16(3, entityType, DeathioApi.EntityType.DebugCircle);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} aabbOffset
 */
DeathioApi.Mob.addAabb = function(builder, aabbOffset) {
  builder.addFieldStruct(4, aabbOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
DeathioApi.Mob.endMob = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @constructor
 */
DeathioApi.Player = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {DeathioApi.Player}
 */
DeathioApi.Player.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {DeathioApi.Player=} obj
 * @returns {DeathioApi.Player}
 */
DeathioApi.Player.getRootAsPlayer = function(bb, obj) {
  return (obj || new DeathioApi.Player).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @returns {flatbuffers.Long}
 */
DeathioApi.Player.prototype.id = function() {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.readUint64(this.bb_pos + offset) : this.bb.createLong(0, 0);
};

/**
 * @param {DeathioApi.Vec2f=} obj
 * @returns {DeathioApi.Vec2f}
 */
DeathioApi.Player.prototype.pos = function(obj) {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? (obj || new DeathioApi.Vec2f).__init(this.bb_pos + offset, this.bb) : null;
};

/**
 * @returns {number}
 */
DeathioApi.Player.prototype.radius = function() {
  var offset = this.bb.__offset(this.bb_pos, 8);
  return offset ? this.bb.readUint16(this.bb_pos + offset) : 0;
};

/**
 * @returns {DeathioApi.EntityType}
 */
DeathioApi.Player.prototype.entityType = function() {
  var offset = this.bb.__offset(this.bb_pos, 10);
  return offset ? /** @type {DeathioApi.EntityType} */ (this.bb.readUint16(this.bb_pos + offset)) : DeathioApi.EntityType.DebugCircle;
};

/**
 * @returns {number}
 */
DeathioApi.Player.prototype.rotation = function() {
  var offset = this.bb.__offset(this.bb_pos, 12);
  return offset ? this.bb.readFloat32(this.bb_pos + offset) : 0.0;
};

/**
 * @returns {boolean}
 */
DeathioApi.Player.prototype.isHit = function() {
  var offset = this.bb.__offset(this.bb_pos, 14);
  return offset ? !!this.bb.readInt8(this.bb_pos + offset) : false;
};

/**
 * @returns {number}
 */
DeathioApi.Player.prototype.actionTick = function() {
  var offset = this.bb.__offset(this.bb_pos, 16);
  return offset ? this.bb.readUint16(this.bb_pos + offset) : 0;
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array}
 */
DeathioApi.Player.prototype.name = function(optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 18);
  return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param {number} index
 * @returns {number}
 */
DeathioApi.Player.prototype.equipment = function(index) {
  var offset = this.bb.__offset(this.bb_pos, 20);
  return offset ? this.bb.readUint8(this.bb.__vector(this.bb_pos + offset) + index) : 0;
};

/**
 * @returns {number}
 */
DeathioApi.Player.prototype.equipmentLength = function() {
  var offset = this.bb.__offset(this.bb_pos, 20);
  return offset ? this.bb.__vector_len(this.bb_pos + offset) : 0;
};

/**
 * @returns {Uint8Array}
 */
DeathioApi.Player.prototype.equipmentArray = function() {
  var offset = this.bb.__offset(this.bb_pos, 20);
  return offset ? new Uint8Array(this.bb.bytes().buffer, this.bb.bytes().byteOffset + this.bb.__vector(this.bb_pos + offset), this.bb.__vector_len(this.bb_pos + offset)) : null;
};

/**
 * @returns {number}
 */
DeathioApi.Player.prototype.health = function() {
  var offset = this.bb.__offset(this.bb_pos, 22);
  return offset ? this.bb.readUint8(this.bb_pos + offset) : 0;
};

/**
 * @returns {number}
 */
DeathioApi.Player.prototype.satiety = function() {
  var offset = this.bb.__offset(this.bb_pos, 24);
  return offset ? this.bb.readUint8(this.bb_pos + offset) : 0;
};

/**
 * @returns {number}
 */
DeathioApi.Player.prototype.bodyTemperature = function() {
  var offset = this.bb.__offset(this.bb_pos, 26);
  return offset ? this.bb.readUint8(this.bb_pos + offset) : 0;
};

/**
 * @param {DeathioApi.AABB=} obj
 * @returns {DeathioApi.AABB}
 */
DeathioApi.Player.prototype.aabb = function(obj) {
  var offset = this.bb.__offset(this.bb_pos, 28);
  return offset ? (obj || new DeathioApi.AABB).__init(this.bb_pos + offset, this.bb) : null;
};

/**
 * @param {flatbuffers.Builder} builder
 */
DeathioApi.Player.startPlayer = function(builder) {
  builder.startObject(13);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Long} id
 */
DeathioApi.Player.addId = function(builder, id) {
  builder.addFieldInt64(0, id, builder.createLong(0, 0));
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} posOffset
 */
DeathioApi.Player.addPos = function(builder, posOffset) {
  builder.addFieldStruct(1, posOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} radius
 */
DeathioApi.Player.addRadius = function(builder, radius) {
  builder.addFieldInt16(2, radius, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {DeathioApi.EntityType} entityType
 */
DeathioApi.Player.addEntityType = function(builder, entityType) {
  builder.addFieldInt16(3, entityType, DeathioApi.EntityType.DebugCircle);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} rotation
 */
DeathioApi.Player.addRotation = function(builder, rotation) {
  builder.addFieldFloat32(4, rotation, 0.0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {boolean} isHit
 */
DeathioApi.Player.addIsHit = function(builder, isHit) {
  builder.addFieldInt8(5, +isHit, +false);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} actionTick
 */
DeathioApi.Player.addActionTick = function(builder, actionTick) {
  builder.addFieldInt16(6, actionTick, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} nameOffset
 */
DeathioApi.Player.addName = function(builder, nameOffset) {
  builder.addFieldOffset(7, nameOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} equipmentOffset
 */
DeathioApi.Player.addEquipment = function(builder, equipmentOffset) {
  builder.addFieldOffset(8, equipmentOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {Array.<number>} data
 * @returns {flatbuffers.Offset}
 */
DeathioApi.Player.createEquipmentVector = function(builder, data) {
  builder.startVector(1, data.length, 1);
  for (var i = data.length - 1; i >= 0; i--) {
    builder.addInt8(data[i]);
  }
  return builder.endVector();
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} numElems
 */
DeathioApi.Player.startEquipmentVector = function(builder, numElems) {
  builder.startVector(1, numElems, 1);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} health
 */
DeathioApi.Player.addHealth = function(builder, health) {
  builder.addFieldInt8(9, health, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} satiety
 */
DeathioApi.Player.addSatiety = function(builder, satiety) {
  builder.addFieldInt8(10, satiety, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} bodyTemperature
 */
DeathioApi.Player.addBodyTemperature = function(builder, bodyTemperature) {
  builder.addFieldInt8(11, bodyTemperature, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} aabbOffset
 */
DeathioApi.Player.addAabb = function(builder, aabbOffset) {
  builder.addFieldStruct(12, aabbOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
DeathioApi.Player.endPlayer = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @constructor
 */
DeathioApi.GameState = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {DeathioApi.GameState}
 */
DeathioApi.GameState.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {DeathioApi.GameState=} obj
 * @returns {DeathioApi.GameState}
 */
DeathioApi.GameState.getRootAsGameState = function(bb, obj) {
  return (obj || new DeathioApi.GameState).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @returns {flatbuffers.Long}
 */
DeathioApi.GameState.prototype.tick = function() {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.readUint64(this.bb_pos + offset) : this.bb.createLong(0, 0);
};

/**
 * @param {DeathioApi.Player=} obj
 * @returns {DeathioApi.Player}
 */
DeathioApi.GameState.prototype.player = function(obj) {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? (obj || new DeathioApi.Player).__init(this.bb.__indirect(this.bb_pos + offset), this.bb) : null;
};

/**
 * @param {number} index
 * @param {DeathioApi.ItemStack=} obj
 * @returns {DeathioApi.ItemStack}
 */
DeathioApi.GameState.prototype.inventory = function(index, obj) {
  var offset = this.bb.__offset(this.bb_pos, 8);
  return offset ? (obj || new DeathioApi.ItemStack).__init(this.bb.__vector(this.bb_pos + offset) + index * 12, this.bb) : null;
};

/**
 * @returns {number}
 */
DeathioApi.GameState.prototype.inventoryLength = function() {
  var offset = this.bb.__offset(this.bb_pos, 8);
  return offset ? this.bb.__vector_len(this.bb_pos + offset) : 0;
};

/**
 * @param {number} index
 * @param {DeathioApi.Entity=} obj
 * @returns {DeathioApi.Entity}
 */
DeathioApi.GameState.prototype.entities = function(index, obj) {
  var offset = this.bb.__offset(this.bb_pos, 10);
  return offset ? (obj || new DeathioApi.Entity).__init(this.bb.__indirect(this.bb.__vector(this.bb_pos + offset) + index * 4), this.bb) : null;
};

/**
 * @returns {number}
 */
DeathioApi.GameState.prototype.entitiesLength = function() {
  var offset = this.bb.__offset(this.bb_pos, 10);
  return offset ? this.bb.__vector_len(this.bb_pos + offset) : 0;
};

/**
 * @param {flatbuffers.Builder} builder
 */
DeathioApi.GameState.startGameState = function(builder) {
  builder.startObject(4);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Long} tick
 */
DeathioApi.GameState.addTick = function(builder, tick) {
  builder.addFieldInt64(0, tick, builder.createLong(0, 0));
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} playerOffset
 */
DeathioApi.GameState.addPlayer = function(builder, playerOffset) {
  builder.addFieldOffset(1, playerOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} inventoryOffset
 */
DeathioApi.GameState.addInventory = function(builder, inventoryOffset) {
  builder.addFieldOffset(2, inventoryOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} numElems
 */
DeathioApi.GameState.startInventoryVector = function(builder, numElems) {
  builder.startVector(12, numElems, 4);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} entitiesOffset
 */
DeathioApi.GameState.addEntities = function(builder, entitiesOffset) {
  builder.addFieldOffset(3, entitiesOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {Array.<flatbuffers.Offset>} data
 * @returns {flatbuffers.Offset}
 */
DeathioApi.GameState.createEntitiesVector = function(builder, data) {
  builder.startVector(4, data.length, 4);
  for (var i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]);
  }
  return builder.endVector();
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} numElems
 */
DeathioApi.GameState.startEntitiesVector = function(builder, numElems) {
  builder.startVector(4, numElems, 4);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
DeathioApi.GameState.endGameState = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} offset
 */
DeathioApi.GameState.finishGameStateBuffer = function(builder, offset) {
  builder.finish(offset);
};

// Exports for Node.js and RequireJS
this.DeathioApi = DeathioApi;
