// automatically generated by the FlatBuffers compiler, do not modify

/**
 * @const
 * @namespace
 */
var BerryhunterApi = BerryhunterApi || {};

/**
 * @enum
 */
BerryhunterApi.EntityType = {
  DebugCircle: 0,
  Border: 1,
  RoundTree: 2,
  MarioTree: 3,
  Character: 4,
  Stone: 5,
  Bronze: 6,
  Iron: 7,
  BerryBush: 8,
  Dodo: 9,
  SaberToothCat: 10,
  Mammoth: 11,
  Placeable: 12
};

/**
 * @enum
 */
BerryhunterApi.AnyEntity = {
  NONE: 0,
  Character: 1,
  Mob: 2,
  Resource: 3,
  Placeable: 4
};

/**
 * @enum
 */
BerryhunterApi.Player = {
  NONE: 0,
  Character: 1,
  Spectator: 2
};

/**
 * @enum
 */
BerryhunterApi.ServerMessageBody = {
  NONE: 0,
  Welcome: 1,
  GameState: 2,
  Accept: 3,
  Obituary: 4,
  EntityMessage: 5,
  Scoreboard: 6
};

/**
 * @constructor
 */
BerryhunterApi.AABB = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {BerryhunterApi.AABB}
 */
BerryhunterApi.AABB.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {BerryhunterApi.Vec2f=} obj
 * @returns {BerryhunterApi.Vec2f}
 */
BerryhunterApi.AABB.prototype.lower = function(obj) {
  return (obj || new BerryhunterApi.Vec2f).__init(this.bb_pos, this.bb);
};

/**
 * @param {BerryhunterApi.Vec2f=} obj
 * @returns {BerryhunterApi.Vec2f}
 */
BerryhunterApi.AABB.prototype.upper = function(obj) {
  return (obj || new BerryhunterApi.Vec2f).__init(this.bb_pos + 8, this.bb);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} lower_x
 * @param {number} lower_y
 * @param {number} upper_x
 * @param {number} upper_y
 * @returns {flatbuffers.Offset}
 */
BerryhunterApi.AABB.createAABB = function(builder, lower_x, lower_y, upper_x, upper_y) {
  builder.prep(4, 16);
  builder.prep(4, 8);
  builder.writeFloat32(upper_y);
  builder.writeFloat32(upper_x);
  builder.prep(4, 8);
  builder.writeFloat32(lower_y);
  builder.writeFloat32(lower_x);
  return builder.offset();
};

/**
 * @constructor
 */
BerryhunterApi.ItemStack = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {BerryhunterApi.ItemStack}
 */
BerryhunterApi.ItemStack.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @returns {number}
 */
BerryhunterApi.ItemStack.prototype.item = function() {
  return this.bb.readUint8(this.bb_pos);
};

/**
 * @returns {number}
 */
BerryhunterApi.ItemStack.prototype.count = function() {
  return this.bb.readUint32(this.bb_pos + 4);
};

/**
 * @returns {number}
 */
BerryhunterApi.ItemStack.prototype.slot = function() {
  return this.bb.readUint8(this.bb_pos + 8);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} item
 * @param {number} count
 * @param {number} slot
 * @returns {flatbuffers.Offset}
 */
BerryhunterApi.ItemStack.createItemStack = function(builder, item, count, slot) {
  builder.prep(4, 12);
  builder.pad(3);
  builder.writeInt8(slot);
  builder.writeInt32(count);
  builder.pad(3);
  builder.writeInt8(item);
  return builder.offset();
};

/**
 * @constructor
 */
BerryhunterApi.OngoingAction = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {BerryhunterApi.OngoingAction}
 */
BerryhunterApi.OngoingAction.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @returns {number}
 */
BerryhunterApi.OngoingAction.prototype.ticksRemaining = function() {
  return this.bb.readUint16(this.bb_pos);
};

/**
 * @returns {BerryhunterApi.ActionType}
 */
BerryhunterApi.OngoingAction.prototype.actionType = function() {
  return /** @type {BerryhunterApi.ActionType} */ (this.bb.readUint8(this.bb_pos + 2));
};

/**
 * @returns {number}
 */
BerryhunterApi.OngoingAction.prototype.item = function() {
  return this.bb.readUint8(this.bb_pos + 3);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} ticks_remaining
 * @param {BerryhunterApi.ActionType} action_type
 * @param {number} item
 * @returns {flatbuffers.Offset}
 */
BerryhunterApi.OngoingAction.createOngoingAction = function(builder, ticks_remaining, action_type, item) {
  builder.prep(2, 4);
  builder.writeInt8(item);
  builder.writeInt8(action_type);
  builder.writeInt16(ticks_remaining);
  return builder.offset();
};

/**
 * @constructor
 */
BerryhunterApi.Entity = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {BerryhunterApi.Entity}
 */
BerryhunterApi.Entity.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {BerryhunterApi.Entity=} obj
 * @returns {BerryhunterApi.Entity}
 */
BerryhunterApi.Entity.getRootAsEntity = function(bb, obj) {
  return (obj || new BerryhunterApi.Entity).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @returns {BerryhunterApi.AnyEntity}
 */
BerryhunterApi.Entity.prototype.eType = function() {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? /** @type {BerryhunterApi.AnyEntity} */ (this.bb.readUint8(this.bb_pos + offset)) : BerryhunterApi.AnyEntity.NONE;
};

/**
 * @param {flatbuffers.Table} obj
 * @returns {?flatbuffers.Table}
 */
BerryhunterApi.Entity.prototype.e = function(obj) {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? this.bb.__union(obj, this.bb_pos + offset) : null;
};

/**
 * @param {flatbuffers.Builder} builder
 */
BerryhunterApi.Entity.startEntity = function(builder) {
  builder.startObject(2);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {BerryhunterApi.AnyEntity} eType
 */
BerryhunterApi.Entity.addEType = function(builder, eType) {
  builder.addFieldInt8(0, eType, BerryhunterApi.AnyEntity.NONE);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} eOffset
 */
BerryhunterApi.Entity.addE = function(builder, eOffset) {
  builder.addFieldOffset(1, eOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
BerryhunterApi.Entity.endEntity = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @constructor
 */
BerryhunterApi.Resource = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {BerryhunterApi.Resource}
 */
BerryhunterApi.Resource.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {BerryhunterApi.Resource=} obj
 * @returns {BerryhunterApi.Resource}
 */
BerryhunterApi.Resource.getRootAsResource = function(bb, obj) {
  return (obj || new BerryhunterApi.Resource).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @returns {flatbuffers.Long}
 */
BerryhunterApi.Resource.prototype.id = function() {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.readUint64(this.bb_pos + offset) : this.bb.createLong(0, 0);
};

/**
 * @returns {BerryhunterApi.EntityType}
 */
BerryhunterApi.Resource.prototype.entityType = function() {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? /** @type {BerryhunterApi.EntityType} */ (this.bb.readUint16(this.bb_pos + offset)) : BerryhunterApi.EntityType.DebugCircle;
};

/**
 * @param {BerryhunterApi.Vec2f=} obj
 * @returns {BerryhunterApi.Vec2f}
 */
BerryhunterApi.Resource.prototype.pos = function(obj) {
  var offset = this.bb.__offset(this.bb_pos, 8);
  return offset ? (obj || new BerryhunterApi.Vec2f).__init(this.bb_pos + offset, this.bb) : null;
};

/**
 * @returns {number}
 */
BerryhunterApi.Resource.prototype.radius = function() {
  var offset = this.bb.__offset(this.bb_pos, 10);
  return offset ? this.bb.readUint16(this.bb_pos + offset) : 0;
};

/**
 * @returns {number}
 */
BerryhunterApi.Resource.prototype.capacity = function() {
  var offset = this.bb.__offset(this.bb_pos, 12);
  return offset ? this.bb.readUint8(this.bb_pos + offset) : 0;
};

/**
 * @returns {number}
 */
BerryhunterApi.Resource.prototype.stock = function() {
  var offset = this.bb.__offset(this.bb_pos, 14);
  return offset ? this.bb.readUint8(this.bb_pos + offset) : 0;
};

/**
 * @param {BerryhunterApi.AABB=} obj
 * @returns {BerryhunterApi.AABB}
 */
BerryhunterApi.Resource.prototype.aabb = function(obj) {
  var offset = this.bb.__offset(this.bb_pos, 16);
  return offset ? (obj || new BerryhunterApi.AABB).__init(this.bb_pos + offset, this.bb) : null;
};

/**
 * @param {flatbuffers.Builder} builder
 */
BerryhunterApi.Resource.startResource = function(builder) {
  builder.startObject(7);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Long} id
 */
BerryhunterApi.Resource.addId = function(builder, id) {
  builder.addFieldInt64(0, id, builder.createLong(0, 0));
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {BerryhunterApi.EntityType} entityType
 */
BerryhunterApi.Resource.addEntityType = function(builder, entityType) {
  builder.addFieldInt16(1, entityType, BerryhunterApi.EntityType.DebugCircle);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} posOffset
 */
BerryhunterApi.Resource.addPos = function(builder, posOffset) {
  builder.addFieldStruct(2, posOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} radius
 */
BerryhunterApi.Resource.addRadius = function(builder, radius) {
  builder.addFieldInt16(3, radius, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} capacity
 */
BerryhunterApi.Resource.addCapacity = function(builder, capacity) {
  builder.addFieldInt8(4, capacity, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} stock
 */
BerryhunterApi.Resource.addStock = function(builder, stock) {
  builder.addFieldInt8(5, stock, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} aabbOffset
 */
BerryhunterApi.Resource.addAabb = function(builder, aabbOffset) {
  builder.addFieldStruct(6, aabbOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
BerryhunterApi.Resource.endResource = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @constructor
 */
BerryhunterApi.Placeable = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {BerryhunterApi.Placeable}
 */
BerryhunterApi.Placeable.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {BerryhunterApi.Placeable=} obj
 * @returns {BerryhunterApi.Placeable}
 */
BerryhunterApi.Placeable.getRootAsPlaceable = function(bb, obj) {
  return (obj || new BerryhunterApi.Placeable).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @returns {flatbuffers.Long}
 */
BerryhunterApi.Placeable.prototype.id = function() {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.readUint64(this.bb_pos + offset) : this.bb.createLong(0, 0);
};

/**
 * @returns {BerryhunterApi.EntityType}
 */
BerryhunterApi.Placeable.prototype.entityType = function() {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? /** @type {BerryhunterApi.EntityType} */ (this.bb.readUint16(this.bb_pos + offset)) : BerryhunterApi.EntityType.DebugCircle;
};

/**
 * @param {BerryhunterApi.Vec2f=} obj
 * @returns {BerryhunterApi.Vec2f}
 */
BerryhunterApi.Placeable.prototype.pos = function(obj) {
  var offset = this.bb.__offset(this.bb_pos, 8);
  return offset ? (obj || new BerryhunterApi.Vec2f).__init(this.bb_pos + offset, this.bb) : null;
};

/**
 * @returns {number}
 */
BerryhunterApi.Placeable.prototype.radius = function() {
  var offset = this.bb.__offset(this.bb_pos, 10);
  return offset ? this.bb.readUint16(this.bb_pos + offset) : 0;
};

/**
 * @returns {number}
 */
BerryhunterApi.Placeable.prototype.item = function() {
  var offset = this.bb.__offset(this.bb_pos, 12);
  return offset ? this.bb.readUint8(this.bb_pos + offset) : 0;
};

/**
 * @param {BerryhunterApi.AABB=} obj
 * @returns {BerryhunterApi.AABB}
 */
BerryhunterApi.Placeable.prototype.aabb = function(obj) {
  var offset = this.bb.__offset(this.bb_pos, 14);
  return offset ? (obj || new BerryhunterApi.AABB).__init(this.bb_pos + offset, this.bb) : null;
};

/**
 * @param {flatbuffers.Builder} builder
 */
BerryhunterApi.Placeable.startPlaceable = function(builder) {
  builder.startObject(6);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Long} id
 */
BerryhunterApi.Placeable.addId = function(builder, id) {
  builder.addFieldInt64(0, id, builder.createLong(0, 0));
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {BerryhunterApi.EntityType} entityType
 */
BerryhunterApi.Placeable.addEntityType = function(builder, entityType) {
  builder.addFieldInt16(1, entityType, BerryhunterApi.EntityType.DebugCircle);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} posOffset
 */
BerryhunterApi.Placeable.addPos = function(builder, posOffset) {
  builder.addFieldStruct(2, posOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} radius
 */
BerryhunterApi.Placeable.addRadius = function(builder, radius) {
  builder.addFieldInt16(3, radius, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} item
 */
BerryhunterApi.Placeable.addItem = function(builder, item) {
  builder.addFieldInt8(4, item, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} aabbOffset
 */
BerryhunterApi.Placeable.addAabb = function(builder, aabbOffset) {
  builder.addFieldStruct(5, aabbOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
BerryhunterApi.Placeable.endPlaceable = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @constructor
 */
BerryhunterApi.Mob = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {BerryhunterApi.Mob}
 */
BerryhunterApi.Mob.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {BerryhunterApi.Mob=} obj
 * @returns {BerryhunterApi.Mob}
 */
BerryhunterApi.Mob.getRootAsMob = function(bb, obj) {
  return (obj || new BerryhunterApi.Mob).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @returns {flatbuffers.Long}
 */
BerryhunterApi.Mob.prototype.id = function() {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.readUint64(this.bb_pos + offset) : this.bb.createLong(0, 0);
};

/**
 * @returns {BerryhunterApi.EntityType}
 */
BerryhunterApi.Mob.prototype.entityType = function() {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? /** @type {BerryhunterApi.EntityType} */ (this.bb.readUint16(this.bb_pos + offset)) : BerryhunterApi.EntityType.DebugCircle;
};

/**
 * @param {BerryhunterApi.Vec2f=} obj
 * @returns {BerryhunterApi.Vec2f}
 */
BerryhunterApi.Mob.prototype.pos = function(obj) {
  var offset = this.bb.__offset(this.bb_pos, 8);
  return offset ? (obj || new BerryhunterApi.Vec2f).__init(this.bb_pos + offset, this.bb) : null;
};

/**
 * @returns {number}
 */
BerryhunterApi.Mob.prototype.radius = function() {
  var offset = this.bb.__offset(this.bb_pos, 10);
  return offset ? this.bb.readUint16(this.bb_pos + offset) : 0;
};

/**
 * @returns {number}
 */
BerryhunterApi.Mob.prototype.rotation = function() {
  var offset = this.bb.__offset(this.bb_pos, 12);
  return offset ? this.bb.readFloat32(this.bb_pos + offset) : 0.0;
};

/**
 * @param {BerryhunterApi.AABB=} obj
 * @returns {BerryhunterApi.AABB}
 */
BerryhunterApi.Mob.prototype.aabb = function(obj) {
  var offset = this.bb.__offset(this.bb_pos, 14);
  return offset ? (obj || new BerryhunterApi.AABB).__init(this.bb_pos + offset, this.bb) : null;
};

/**
 * @returns {number}
 */
BerryhunterApi.Mob.prototype.mobId = function() {
  var offset = this.bb.__offset(this.bb_pos, 16);
  return offset ? this.bb.readUint16(this.bb_pos + offset) : 0;
};

/**
 * @param {flatbuffers.Builder} builder
 */
BerryhunterApi.Mob.startMob = function(builder) {
  builder.startObject(7);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Long} id
 */
BerryhunterApi.Mob.addId = function(builder, id) {
  builder.addFieldInt64(0, id, builder.createLong(0, 0));
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {BerryhunterApi.EntityType} entityType
 */
BerryhunterApi.Mob.addEntityType = function(builder, entityType) {
  builder.addFieldInt16(1, entityType, BerryhunterApi.EntityType.DebugCircle);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} posOffset
 */
BerryhunterApi.Mob.addPos = function(builder, posOffset) {
  builder.addFieldStruct(2, posOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} radius
 */
BerryhunterApi.Mob.addRadius = function(builder, radius) {
  builder.addFieldInt16(3, radius, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} rotation
 */
BerryhunterApi.Mob.addRotation = function(builder, rotation) {
  builder.addFieldFloat32(4, rotation, 0.0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} aabbOffset
 */
BerryhunterApi.Mob.addAabb = function(builder, aabbOffset) {
  builder.addFieldStruct(5, aabbOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} mobId
 */
BerryhunterApi.Mob.addMobId = function(builder, mobId) {
  builder.addFieldInt16(6, mobId, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
BerryhunterApi.Mob.endMob = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @constructor
 */
BerryhunterApi.Character = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {BerryhunterApi.Character}
 */
BerryhunterApi.Character.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {BerryhunterApi.Character=} obj
 * @returns {BerryhunterApi.Character}
 */
BerryhunterApi.Character.getRootAsCharacter = function(bb, obj) {
  return (obj || new BerryhunterApi.Character).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @returns {flatbuffers.Long}
 */
BerryhunterApi.Character.prototype.id = function() {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.readUint64(this.bb_pos + offset) : this.bb.createLong(0, 0);
};

/**
 * @returns {BerryhunterApi.EntityType}
 */
BerryhunterApi.Character.prototype.entityType = function() {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? /** @type {BerryhunterApi.EntityType} */ (this.bb.readUint16(this.bb_pos + offset)) : BerryhunterApi.EntityType.DebugCircle;
};

/**
 * @param {BerryhunterApi.Vec2f=} obj
 * @returns {BerryhunterApi.Vec2f}
 */
BerryhunterApi.Character.prototype.pos = function(obj) {
  var offset = this.bb.__offset(this.bb_pos, 8);
  return offset ? (obj || new BerryhunterApi.Vec2f).__init(this.bb_pos + offset, this.bb) : null;
};

/**
 * @returns {number}
 */
BerryhunterApi.Character.prototype.radius = function() {
  var offset = this.bb.__offset(this.bb_pos, 10);
  return offset ? this.bb.readUint16(this.bb_pos + offset) : 0;
};

/**
 * @returns {number}
 */
BerryhunterApi.Character.prototype.rotation = function() {
  var offset = this.bb.__offset(this.bb_pos, 12);
  return offset ? this.bb.readFloat32(this.bb_pos + offset) : 0.0;
};

/**
 * @returns {boolean}
 */
BerryhunterApi.Character.prototype.isHit = function() {
  var offset = this.bb.__offset(this.bb_pos, 14);
  return offset ? !!this.bb.readInt8(this.bb_pos + offset) : false;
};

/**
 * @param {BerryhunterApi.OngoingAction=} obj
 * @returns {BerryhunterApi.OngoingAction}
 */
BerryhunterApi.Character.prototype.currentAction = function(obj) {
  var offset = this.bb.__offset(this.bb_pos, 16);
  return offset ? (obj || new BerryhunterApi.OngoingAction).__init(this.bb_pos + offset, this.bb) : null;
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array}
 */
BerryhunterApi.Character.prototype.name = function(optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 18);
  return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param {number} index
 * @returns {number}
 */
BerryhunterApi.Character.prototype.equipment = function(index) {
  var offset = this.bb.__offset(this.bb_pos, 20);
  return offset ? this.bb.readUint8(this.bb.__vector(this.bb_pos + offset) + index) : 0;
};

/**
 * @returns {number}
 */
BerryhunterApi.Character.prototype.equipmentLength = function() {
  var offset = this.bb.__offset(this.bb_pos, 20);
  return offset ? this.bb.__vector_len(this.bb_pos + offset) : 0;
};

/**
 * @returns {Uint8Array}
 */
BerryhunterApi.Character.prototype.equipmentArray = function() {
  var offset = this.bb.__offset(this.bb_pos, 20);
  return offset ? new Uint8Array(this.bb.bytes().buffer, this.bb.bytes().byteOffset + this.bb.__vector(this.bb_pos + offset), this.bb.__vector_len(this.bb_pos + offset)) : null;
};

/**
 * @returns {number}
 */
BerryhunterApi.Character.prototype.health = function() {
  var offset = this.bb.__offset(this.bb_pos, 22);
  return offset ? this.bb.readUint32(this.bb_pos + offset) : 0;
};

/**
 * @returns {number}
 */
BerryhunterApi.Character.prototype.satiety = function() {
  var offset = this.bb.__offset(this.bb_pos, 24);
  return offset ? this.bb.readUint32(this.bb_pos + offset) : 0;
};

/**
 * @returns {number}
 */
BerryhunterApi.Character.prototype.bodyTemperature = function() {
  var offset = this.bb.__offset(this.bb_pos, 26);
  return offset ? this.bb.readUint32(this.bb_pos + offset) : 0;
};

/**
 * @param {BerryhunterApi.AABB=} obj
 * @returns {BerryhunterApi.AABB}
 */
BerryhunterApi.Character.prototype.aabb = function(obj) {
  var offset = this.bb.__offset(this.bb_pos, 28);
  return offset ? (obj || new BerryhunterApi.AABB).__init(this.bb_pos + offset, this.bb) : null;
};

/**
 * @param {flatbuffers.Builder} builder
 */
BerryhunterApi.Character.startCharacter = function(builder) {
  builder.startObject(13);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Long} id
 */
BerryhunterApi.Character.addId = function(builder, id) {
  builder.addFieldInt64(0, id, builder.createLong(0, 0));
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {BerryhunterApi.EntityType} entityType
 */
BerryhunterApi.Character.addEntityType = function(builder, entityType) {
  builder.addFieldInt16(1, entityType, BerryhunterApi.EntityType.DebugCircle);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} posOffset
 */
BerryhunterApi.Character.addPos = function(builder, posOffset) {
  builder.addFieldStruct(2, posOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} radius
 */
BerryhunterApi.Character.addRadius = function(builder, radius) {
  builder.addFieldInt16(3, radius, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} rotation
 */
BerryhunterApi.Character.addRotation = function(builder, rotation) {
  builder.addFieldFloat32(4, rotation, 0.0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {boolean} isHit
 */
BerryhunterApi.Character.addIsHit = function(builder, isHit) {
  builder.addFieldInt8(5, +isHit, +false);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} currentActionOffset
 */
BerryhunterApi.Character.addCurrentAction = function(builder, currentActionOffset) {
  builder.addFieldStruct(6, currentActionOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} nameOffset
 */
BerryhunterApi.Character.addName = function(builder, nameOffset) {
  builder.addFieldOffset(7, nameOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} equipmentOffset
 */
BerryhunterApi.Character.addEquipment = function(builder, equipmentOffset) {
  builder.addFieldOffset(8, equipmentOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {Array.<number>} data
 * @returns {flatbuffers.Offset}
 */
BerryhunterApi.Character.createEquipmentVector = function(builder, data) {
  builder.startVector(1, data.length, 1);
  for (var i = data.length - 1; i >= 0; i--) {
    builder.addInt8(data[i]);
  }
  return builder.endVector();
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} numElems
 */
BerryhunterApi.Character.startEquipmentVector = function(builder, numElems) {
  builder.startVector(1, numElems, 1);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} health
 */
BerryhunterApi.Character.addHealth = function(builder, health) {
  builder.addFieldInt32(9, health, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} satiety
 */
BerryhunterApi.Character.addSatiety = function(builder, satiety) {
  builder.addFieldInt32(10, satiety, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} bodyTemperature
 */
BerryhunterApi.Character.addBodyTemperature = function(builder, bodyTemperature) {
  builder.addFieldInt32(11, bodyTemperature, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} aabbOffset
 */
BerryhunterApi.Character.addAabb = function(builder, aabbOffset) {
  builder.addFieldStruct(12, aabbOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
BerryhunterApi.Character.endCharacter = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @constructor
 */
BerryhunterApi.Spectator = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {BerryhunterApi.Spectator}
 */
BerryhunterApi.Spectator.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {BerryhunterApi.Spectator=} obj
 * @returns {BerryhunterApi.Spectator}
 */
BerryhunterApi.Spectator.getRootAsSpectator = function(bb, obj) {
  return (obj || new BerryhunterApi.Spectator).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @returns {flatbuffers.Long}
 */
BerryhunterApi.Spectator.prototype.id = function() {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.readUint64(this.bb_pos + offset) : this.bb.createLong(0, 0);
};

/**
 * @param {BerryhunterApi.Vec2f=} obj
 * @returns {BerryhunterApi.Vec2f}
 */
BerryhunterApi.Spectator.prototype.pos = function(obj) {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? (obj || new BerryhunterApi.Vec2f).__init(this.bb_pos + offset, this.bb) : null;
};

/**
 * @param {flatbuffers.Builder} builder
 */
BerryhunterApi.Spectator.startSpectator = function(builder) {
  builder.startObject(2);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Long} id
 */
BerryhunterApi.Spectator.addId = function(builder, id) {
  builder.addFieldInt64(0, id, builder.createLong(0, 0));
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} posOffset
 */
BerryhunterApi.Spectator.addPos = function(builder, posOffset) {
  builder.addFieldStruct(1, posOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
BerryhunterApi.Spectator.endSpectator = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @constructor
 */
BerryhunterApi.GameState = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {BerryhunterApi.GameState}
 */
BerryhunterApi.GameState.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {BerryhunterApi.GameState=} obj
 * @returns {BerryhunterApi.GameState}
 */
BerryhunterApi.GameState.getRootAsGameState = function(bb, obj) {
  return (obj || new BerryhunterApi.GameState).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @returns {flatbuffers.Long}
 */
BerryhunterApi.GameState.prototype.tick = function() {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.readUint64(this.bb_pos + offset) : this.bb.createLong(0, 0);
};

/**
 * @returns {BerryhunterApi.Player}
 */
BerryhunterApi.GameState.prototype.playerType = function() {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? /** @type {BerryhunterApi.Player} */ (this.bb.readUint8(this.bb_pos + offset)) : BerryhunterApi.Player.NONE;
};

/**
 * @param {flatbuffers.Table} obj
 * @returns {?flatbuffers.Table}
 */
BerryhunterApi.GameState.prototype.player = function(obj) {
  var offset = this.bb.__offset(this.bb_pos, 8);
  return offset ? this.bb.__union(obj, this.bb_pos + offset) : null;
};

/**
 * @param {number} index
 * @param {BerryhunterApi.ItemStack=} obj
 * @returns {BerryhunterApi.ItemStack}
 */
BerryhunterApi.GameState.prototype.inventory = function(index, obj) {
  var offset = this.bb.__offset(this.bb_pos, 10);
  return offset ? (obj || new BerryhunterApi.ItemStack).__init(this.bb.__vector(this.bb_pos + offset) + index * 12, this.bb) : null;
};

/**
 * @returns {number}
 */
BerryhunterApi.GameState.prototype.inventoryLength = function() {
  var offset = this.bb.__offset(this.bb_pos, 10);
  return offset ? this.bb.__vector_len(this.bb_pos + offset) : 0;
};

/**
 * @param {number} index
 * @param {BerryhunterApi.Entity=} obj
 * @returns {BerryhunterApi.Entity}
 */
BerryhunterApi.GameState.prototype.entities = function(index, obj) {
  var offset = this.bb.__offset(this.bb_pos, 12);
  return offset ? (obj || new BerryhunterApi.Entity).__init(this.bb.__indirect(this.bb.__vector(this.bb_pos + offset) + index * 4), this.bb) : null;
};

/**
 * @returns {number}
 */
BerryhunterApi.GameState.prototype.entitiesLength = function() {
  var offset = this.bb.__offset(this.bb_pos, 12);
  return offset ? this.bb.__vector_len(this.bb_pos + offset) : 0;
};

/**
 * @param {flatbuffers.Builder} builder
 */
BerryhunterApi.GameState.startGameState = function(builder) {
  builder.startObject(5);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Long} tick
 */
BerryhunterApi.GameState.addTick = function(builder, tick) {
  builder.addFieldInt64(0, tick, builder.createLong(0, 0));
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {BerryhunterApi.Player} playerType
 */
BerryhunterApi.GameState.addPlayerType = function(builder, playerType) {
  builder.addFieldInt8(1, playerType, BerryhunterApi.Player.NONE);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} playerOffset
 */
BerryhunterApi.GameState.addPlayer = function(builder, playerOffset) {
  builder.addFieldOffset(2, playerOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} inventoryOffset
 */
BerryhunterApi.GameState.addInventory = function(builder, inventoryOffset) {
  builder.addFieldOffset(3, inventoryOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} numElems
 */
BerryhunterApi.GameState.startInventoryVector = function(builder, numElems) {
  builder.startVector(12, numElems, 4);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} entitiesOffset
 */
BerryhunterApi.GameState.addEntities = function(builder, entitiesOffset) {
  builder.addFieldOffset(4, entitiesOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {Array.<flatbuffers.Offset>} data
 * @returns {flatbuffers.Offset}
 */
BerryhunterApi.GameState.createEntitiesVector = function(builder, data) {
  builder.startVector(4, data.length, 4);
  for (var i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]);
  }
  return builder.endVector();
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} numElems
 */
BerryhunterApi.GameState.startEntitiesVector = function(builder, numElems) {
  builder.startVector(4, numElems, 4);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
BerryhunterApi.GameState.endGameState = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @constructor
 */
BerryhunterApi.Welcome = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {BerryhunterApi.Welcome}
 */
BerryhunterApi.Welcome.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {BerryhunterApi.Welcome=} obj
 * @returns {BerryhunterApi.Welcome}
 */
BerryhunterApi.Welcome.getRootAsWelcome = function(bb, obj) {
  return (obj || new BerryhunterApi.Welcome).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array}
 */
BerryhunterApi.Welcome.prototype.serverName = function(optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @returns {number}
 */
BerryhunterApi.Welcome.prototype.mapRadius = function() {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? this.bb.readFloat32(this.bb_pos + offset) : 0.0;
};

/**
 * @param {flatbuffers.Builder} builder
 */
BerryhunterApi.Welcome.startWelcome = function(builder) {
  builder.startObject(2);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} serverNameOffset
 */
BerryhunterApi.Welcome.addServerName = function(builder, serverNameOffset) {
  builder.addFieldOffset(0, serverNameOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} mapRadius
 */
BerryhunterApi.Welcome.addMapRadius = function(builder, mapRadius) {
  builder.addFieldFloat32(1, mapRadius, 0.0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
BerryhunterApi.Welcome.endWelcome = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @constructor
 */
BerryhunterApi.Accept = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {BerryhunterApi.Accept}
 */
BerryhunterApi.Accept.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {BerryhunterApi.Accept=} obj
 * @returns {BerryhunterApi.Accept}
 */
BerryhunterApi.Accept.getRootAsAccept = function(bb, obj) {
  return (obj || new BerryhunterApi.Accept).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.Builder} builder
 */
BerryhunterApi.Accept.startAccept = function(builder) {
  builder.startObject(0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
BerryhunterApi.Accept.endAccept = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @constructor
 */
BerryhunterApi.Obituary = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {BerryhunterApi.Obituary}
 */
BerryhunterApi.Obituary.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {BerryhunterApi.Obituary=} obj
 * @returns {BerryhunterApi.Obituary}
 */
BerryhunterApi.Obituary.getRootAsObituary = function(bb, obj) {
  return (obj || new BerryhunterApi.Obituary).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.Builder} builder
 */
BerryhunterApi.Obituary.startObituary = function(builder) {
  builder.startObject(0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
BerryhunterApi.Obituary.endObituary = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @constructor
 */
BerryhunterApi.EntityMessage = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {BerryhunterApi.EntityMessage}
 */
BerryhunterApi.EntityMessage.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {BerryhunterApi.EntityMessage=} obj
 * @returns {BerryhunterApi.EntityMessage}
 */
BerryhunterApi.EntityMessage.getRootAsEntityMessage = function(bb, obj) {
  return (obj || new BerryhunterApi.EntityMessage).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @returns {flatbuffers.Long}
 */
BerryhunterApi.EntityMessage.prototype.entityId = function() {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.readUint64(this.bb_pos + offset) : this.bb.createLong(0, 0);
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array}
 */
BerryhunterApi.EntityMessage.prototype.message = function(optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param {flatbuffers.Builder} builder
 */
BerryhunterApi.EntityMessage.startEntityMessage = function(builder) {
  builder.startObject(2);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Long} entityId
 */
BerryhunterApi.EntityMessage.addEntityId = function(builder, entityId) {
  builder.addFieldInt64(0, entityId, builder.createLong(0, 0));
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} messageOffset
 */
BerryhunterApi.EntityMessage.addMessage = function(builder, messageOffset) {
  builder.addFieldOffset(1, messageOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
BerryhunterApi.EntityMessage.endEntityMessage = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @constructor
 */
BerryhunterApi.ScoreboardPlayer = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {BerryhunterApi.ScoreboardPlayer}
 */
BerryhunterApi.ScoreboardPlayer.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {BerryhunterApi.ScoreboardPlayer=} obj
 * @returns {BerryhunterApi.ScoreboardPlayer}
 */
BerryhunterApi.ScoreboardPlayer.getRootAsScoreboardPlayer = function(bb, obj) {
  return (obj || new BerryhunterApi.ScoreboardPlayer).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array}
 */
BerryhunterApi.ScoreboardPlayer.prototype.name = function(optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @returns {flatbuffers.Long}
 */
BerryhunterApi.ScoreboardPlayer.prototype.score = function() {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? this.bb.readUint64(this.bb_pos + offset) : this.bb.createLong(0, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 */
BerryhunterApi.ScoreboardPlayer.startScoreboardPlayer = function(builder) {
  builder.startObject(2);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} nameOffset
 */
BerryhunterApi.ScoreboardPlayer.addName = function(builder, nameOffset) {
  builder.addFieldOffset(0, nameOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Long} score
 */
BerryhunterApi.ScoreboardPlayer.addScore = function(builder, score) {
  builder.addFieldInt64(1, score, builder.createLong(0, 0));
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
BerryhunterApi.ScoreboardPlayer.endScoreboardPlayer = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @constructor
 */
BerryhunterApi.Scoreboard = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {BerryhunterApi.Scoreboard}
 */
BerryhunterApi.Scoreboard.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {BerryhunterApi.Scoreboard=} obj
 * @returns {BerryhunterApi.Scoreboard}
 */
BerryhunterApi.Scoreboard.getRootAsScoreboard = function(bb, obj) {
  return (obj || new BerryhunterApi.Scoreboard).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {number} index
 * @param {BerryhunterApi.ScoreboardPlayer=} obj
 * @returns {BerryhunterApi.ScoreboardPlayer}
 */
BerryhunterApi.Scoreboard.prototype.players = function(index, obj) {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? (obj || new BerryhunterApi.ScoreboardPlayer).__init(this.bb.__indirect(this.bb.__vector(this.bb_pos + offset) + index * 4), this.bb) : null;
};

/**
 * @returns {number}
 */
BerryhunterApi.Scoreboard.prototype.playersLength = function() {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.__vector_len(this.bb_pos + offset) : 0;
};

/**
 * @param {flatbuffers.Builder} builder
 */
BerryhunterApi.Scoreboard.startScoreboard = function(builder) {
  builder.startObject(1);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} playersOffset
 */
BerryhunterApi.Scoreboard.addPlayers = function(builder, playersOffset) {
  builder.addFieldOffset(0, playersOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {Array.<flatbuffers.Offset>} data
 * @returns {flatbuffers.Offset}
 */
BerryhunterApi.Scoreboard.createPlayersVector = function(builder, data) {
  builder.startVector(4, data.length, 4);
  for (var i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]);
  }
  return builder.endVector();
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} numElems
 */
BerryhunterApi.Scoreboard.startPlayersVector = function(builder, numElems) {
  builder.startVector(4, numElems, 4);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
BerryhunterApi.Scoreboard.endScoreboard = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @constructor
 */
BerryhunterApi.ServerMessage = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {BerryhunterApi.ServerMessage}
 */
BerryhunterApi.ServerMessage.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {BerryhunterApi.ServerMessage=} obj
 * @returns {BerryhunterApi.ServerMessage}
 */
BerryhunterApi.ServerMessage.getRootAsServerMessage = function(bb, obj) {
  return (obj || new BerryhunterApi.ServerMessage).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @returns {BerryhunterApi.ServerMessageBody}
 */
BerryhunterApi.ServerMessage.prototype.bodyType = function() {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? /** @type {BerryhunterApi.ServerMessageBody} */ (this.bb.readUint8(this.bb_pos + offset)) : BerryhunterApi.ServerMessageBody.NONE;
};

/**
 * @param {flatbuffers.Table} obj
 * @returns {?flatbuffers.Table}
 */
BerryhunterApi.ServerMessage.prototype.body = function(obj) {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? this.bb.__union(obj, this.bb_pos + offset) : null;
};

/**
 * @param {flatbuffers.Builder} builder
 */
BerryhunterApi.ServerMessage.startServerMessage = function(builder) {
  builder.startObject(2);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {BerryhunterApi.ServerMessageBody} bodyType
 */
BerryhunterApi.ServerMessage.addBodyType = function(builder, bodyType) {
  builder.addFieldInt8(0, bodyType, BerryhunterApi.ServerMessageBody.NONE);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} bodyOffset
 */
BerryhunterApi.ServerMessage.addBody = function(builder, bodyOffset) {
  builder.addFieldOffset(1, bodyOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
BerryhunterApi.ServerMessage.endServerMessage = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} offset
 */
BerryhunterApi.ServerMessage.finishServerMessageBuffer = function(builder, offset) {
  builder.finish(offset);
};

// Exports for Node.js and RequireJS
this.BerryhunterApi = BerryhunterApi;
