// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package ChieftainApi

import "strconv"

type ClientMessageBody byte

const (
	ClientMessageBodyNONE       ClientMessageBody = 0
	ClientMessageBodyScoreboard ClientMessageBody = 1
)

var EnumNamesClientMessageBody = map[ClientMessageBody]string{
	ClientMessageBodyNONE:       "NONE",
	ClientMessageBodyScoreboard: "Scoreboard",
}

var EnumValuesClientMessageBody = map[string]ClientMessageBody{
	"NONE":       ClientMessageBodyNONE,
	"Scoreboard": ClientMessageBodyScoreboard,
}

func (v ClientMessageBody) String() string {
	if s, ok := EnumNamesClientMessageBody[v]; ok {
		return s
	}
	return "ClientMessageBody(" + strconv.FormatInt(int64(v), 10) + ")"
}
