"use strict";

var Constants = {
	BASE_MOVEMENT_SPEED: 5,
	GRID_SPACING: 100,
	FIELDS_IN_QUADRANT: 8,
	SHOW_FPS: true,
	PIXEL_PER_METRE: 30
};

Constants.QUADRANT_SIZE= Constants.GRID_SPACING * Constants.FIELDS_IN_QUADRANT;